import { Card, Category } from './cards';
import { orangeCardList } from './orangeBinder';
import purpleBinder from './purpleBinder';

// Green faction cards (from deckOne.ts - uncommented and cleaned)
const greenBinder: Card[] = [
  {
    faction: 'green-border',
    id: 1,
    category: "ENTITY" as Category,
    name: "PingWin",
    rezCost: 1,
    soul: 1,
    ash: 0,
    subTypes: ["JAW"],
    power: 1,
    HP: 4,
    timer: 3,
    abilities: [
      { name: "Acidic" },
      { name: "Armored" },
      { name: "Defensive" }
    ],
    description: "",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 2,
    category: "ENTITY" as Category,
    name: "Ram",
    rezCost: 3,
    soul: 0,
    ash: 2,
    subTypes: ["JAW"],
    power: 2,
    HP: 2,
    timer: 2,
    abilities: [
      { name: "Locality" },
      { name: "Defensive" }
    ],
    description: "Exhaust ➔ Target friendly Sym or Snip gains Develop 2.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 3,
    category: "ENTITY" as Category,
    name: "PawPups",
    rezCost: 1,
    soul: 1,
    ash: 0,
    subTypes: ["JAW"],
    power: 1,
    HP: 3,
    timer: 1,
    abilities: [
      { name: "Barricade" },
      { name: "Devious" },
      { name: "Syndrome", amount: 2 },
      { name: "Defensive" }
    ],
    description: "",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 4,
    category: "ENTITY" as Category,
    name: "ScriptKitty",
    rezCost: 3,
    soul: 2,
    ash: 0,
    subTypes: ["JAW"],
    power: 3,
    HP: 2,
    timer: 2,
    abilities: [
      { name: "Stealth" },
      { name: "Pounce" },
      { name: "Ambush" },
      { name: "Defensive" }
    ],
    description: "",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 5,
    category: "ENTITY" as Category,
    name: "DeadHerring",
    rezCost: 2,
    soul: 0,
    ash: 3,
    subTypes: ["JAW"],
    power: 2,
    HP: 4,
    timer: 3,
    abilities: [
      { name: "Rotten" },
      { name: "Deathless" },
      { name: "Defensive" }
    ],
    description: "",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 6,
    category: "ENTITY" as Category,
    name: "Bau",
    rezCost: 3,
    soul: 3,
    ash: 0,
    subTypes: ["JAW"],
    power: 4,
    HP: 6,
    timer: 3,
    abilities: [
      { name: "Enchanted" },
      { name: "Dividend", amount: 3 },
      { name: "Syndrome", amount: 3 },
      { name: "Defensive" }
    ],
    description: "",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 7,
    category: "ENTITY" as Category,
    name: "Lich Queen",
    rezCost: 2,
    soul: 0,
    ash: 5,
    subTypes: [],
    power: 5,
    HP: 10,
    timer: 4,
    abilities: [
      { name: "Deathless" },
      { name: "Enchanted" },
      { name: "Syndrome", amount: 3 },
      { name: "Cursed" }
    ],
    description: "Dominance ➔ Return 3 cards in your Limbo to HeadSpace.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 8,
    category: "ENTITY" as Category,
    name: "Plague Priestess",
    rezCost: 2,
    soul: 1,
    ash: 0,
    subTypes: [],
    power: 2,
    HP: 3,
    timer: 3,
    abilities: [
      { name: "Stealth" },
      { name: "Syndrome", amount: 3 }
    ],
    description: "Target entity gains +5 HP and Decay.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 9,
    category: "ENTITY" as Category,
    name: "Lamia",
    rezCost: 4,
    soul: 1,
    ash: 0,
    subTypes: [],
    power: 2,
    HP: 3,
    timer: 3,
    abilities: [
      { name: "Acidic" },
      { name: "Syndrome", amount: 2 }
    ],
    description: "Gain control of target Decaying entity and give it Freeze 1.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 10,
    category: "ENTITY" as Category,
    name: "Incubus",
    rezCost: 1,
    soul: 2,
    ash: 0,
    subTypes: [],
    power: 2,
    HP: 4,
    timer: 3,
    abilities: [
      { name: "Exhaust", effect: "Target entity gains Vengeance 3 and Decay 3" }
    ],
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 11,
    category: "ENTITY" as Category,
    name: "Harpies",
    rezCost: 6,
    soul: 1,
    ash: 0,
    subTypes: [],
    power: 3,
    HP: 6,
    timer: 3,
    abilities: [
      { name: "Rapture", amount: 3 },
      { name: "Necrotic", amount: 3 },
      { name: "Syndrome", amount: 3 }
    ],
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 12,
    category: "ENTITY" as Category,
    name: "Surrogate",
    rezCost: 1,
    soul: 0,
    ash: 2,
    subTypes: [],
    power: 2,
    HP: 5,
    timer: 3,
    abilities: [
      { name: "Acidic" },
      { name: "Rotten" },
      { name: "Locality" },
      { name: "Syndrome", amount: 1 }
    ],
    description: "Dreamers have Devious.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 13,
    category: "ENTITY" as Category,
    name: "Flesh Hive",
    rezCost: 2,
    soul: 3,
    ash: 0,
    subTypes: [],
    power: 6,
    HP: 8,
    timer: 4,
    abilities: [
      { name: "Deathless" },
      { name: "Devour" },
      { name: "Charge", amount: 1 },
      { name: "Syndrome", amount: 2 },
      { name: "Cursed" }
    ],
    description: "Whenever a Decaying entity dies, +1 Fate and +2 Overload.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 14,
    category: "ENTITY" as Category,
    name: "Husk",
    rezCost: 3,
    soul: 3,
    ash: 0,
    subTypes: [],
    power: 5,
    HP: 6,
    timer: 4,
    abilities: [
      { name: "Ambush", amount: 3 },
      { name: "Devious" },
      { name: "Aggressive" }
    ],
    description: "",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 15,
    category: "ENTITY" as Category,
    name: "Hostess",
    rezCost: 5,
    soul: 1,
    ash: 0,
    subTypes: [],
    power: 3,
    HP: 2,
    timer: 3,
    abilities: [
      { name: "Stealth" },
      { name: "Locality" },
      { name: "Syndrome", amount: 1 }
    ],
    description: "Transfer all friendly Decay to target entity.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 16,
    category: "ENTITY" as Category,
    name: "WebCrawler",
    rezCost: 4,
    soul: 0,
    ash: 4,
    subTypes: [],
    power: 4,
    HP: 8,
    timer: 4,
    abilities: [
      { name: "Ambush", amount: 2 },
      { name: "Barricade", amount: 2 },
      { name: "Devour" },
      { name: "Aggressive" }
    ],
    description: "",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 17,
    category: "ENTITY" as Category,
    name: "Terminal",
    rezCost: 3,
    soul: 2,
    ash: 0,
    subTypes: [],
    power: 3,
    HP: 6,
    timer: 4,
    abilities: [
      { name: "Covenant" },
      { name: "Syndrome", amount: 2 },
      { name: "Gravity" }
    ],
    description: "Whenever a player Ascends a card, +3 Bits.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 18,
    category: "ENTITY" as Category,
    name: "Remnant",
    rezCost: 2,
    soul: 2,
    ash: 0,
    subTypes: [],
    power: 4,
    HP: 6,
    timer: 4,
    abilities: [
      { name: "Deathless" },
      { name: "Necrotic", amount: 2 },
      { name: "Syndrome", amount: 2 }
    ],
    description: "",
    magi: false,
    phys: true,
    tech: false,
  }
];

// Gray faction cards (from grayCardsNew.txt)
const grayBinder: Card[] = [
  // Magi Entities
  {
    faction: 'gray-border',
    id: 401,
    category: "ENTITY" as Category,
    name: "Magician",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 3,
    timer: 3,
    subTypes: [],
    keywords: "Dividend, Duplicate, Stealth 2",
    abilities: [
      { name: "Dividend" },
      { name: "Duplicate" },
      { name: "Stealth", amount: 2 }
    ],
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 402,
    category: "ENTITY" as Category,
    name: "Cryptid",
    rezCost: 2,
    soul: 2,
    ash: 0,
    power: 5,
    HP: 4,
    timer: 4,
    subTypes: [],
    keywords: "Charge 2, Devour, Override, Necrotic 2",
    abilities: [
      { name: "Charge", amount: 2 },
      { name: "Devour" },
      { name: "Override" },
      { name: "Necrotic", amount: 2 }
    ],
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 403,
    category: "ENTITY" as Category,
    name: "Familiar",
    rezCost: 1,
    soul: 0,
    ash: 1,
    power: 0,
    HP: 1,
    timer: 1,
    subTypes: [],
    keywords: "Vengeance 3, Pounce",
    abilities: [
      { name: "Vengeance", amount: 3 },
      { name: "Pounce" }
    ],
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 404,
    category: "ENTITY" as Category,
    name: "Banshee",
    rezCost: 2,
    soul: 3,
    ash: 0,
    power: 3,
    HP: 4,
    timer: 3,
    subTypes: [],
    keywords: "Stealth, Soulless, Horrific, Defensive",
    abilities: [
      { name: "Stealth" },
      { name: "Soulless" },
      { name: "Horrific" },
      { name: "Defensive" }
    ],
    description: "Dominance ➔ Gain control of target exhausted Online entity.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 405,
    category: "ENTITY" as Category,
    name: "Phoenix",
    rezCost: 1,
    soul: 0,
    ash: 5,
    power: 3,
    HP: 3,
    timer: 2,
    subTypes: [],
    keywords: "Charge, Deathless, Locality",
    abilities: [
      { name: "Charge" },
      { name: "Deathless" },
      { name: "Locality" }
    ],
    description: "Deal 2 Damage to all Entities",
    magi: true,
    phys: false,
    tech: false,
  },
  // Physical Entities
  {
    faction: 'gray-border',
    id: 406,
    category: "ENTITY" as Category,
    name: "Dingo",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 2,
    timer: 2,
    subTypes: [],
    keywords: "Pounce, Charge, Ambush",
    abilities: [
      { name: "Pounce" },
      { name: "Charge" },
      { name: "Ambush" }
    ],
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 407,
    category: "ENTITY" as Category,
    name: "Conscripts",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 6,
    timer: 3,
    subTypes: [],
    keywords: "Barricade, Defensive",
    abilities: [
      { name: "Barricade" },
      { name: "Defensive" }
    ],
    description: "Exhaust ➔ Barricade 3",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 408,
    category: "ENTITY" as Category,
    name: "Artillery",
    rezCost: 4,
    soul: 2,
    ash: 0,
    power: 4,
    HP: 3,
    timer: 3,
    subTypes: [],
    keywords: "Sting 4, Ambush 2, Aggressive, Locality",
    abilities: [
      { name: "Sting", amount: 4 },
      { name: "Ambush", amount: 2 },
      { name: "Aggressive" },
      { name: "Locality" }
    ],
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 409,
    category: "ENTITY" as Category,
    name: "Firing Squad",
    rezCost: 2,
    soul: 3,
    ash: 0,
    power: 3,
    HP: 2,
    timer: 3,
    subTypes: [],
    keywords: "Duelist, Charge 2, Pounce, Duplicate 2, Aggro",
    abilities: [
      { name: "Duelist" },
      { name: "Charge", amount: 2 },
      { name: "Pounce" },
      { name: "Duplicate", amount: 2 },
      { name: "Aggro" }
    ],
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 410,
    category: "ENTITY" as Category,
    name: "Combat Medic",
    rezCost: 1,
    soul: 0,
    ash: 2,
    power: 2,
    HP: 4,
    timer: 2,
    subTypes: [],
    keywords: "Stealth, Locality, Defensive",
    abilities: [
      { name: "Stealth" },
      { name: "Locality" },
      { name: "Defensive" }
    ],
    description: "Target entity gains +6 Health and Charge.",
    magi: false,
    phys: true,
    tech: false,
  },
  // JAW Entities (Tech Affinity)
  {
    faction: 'gray-border',
    id: 411,
    category: "ENTITY" as Category,
    name: "Troll",
    rezCost: 3,
    soul: 2,
    ash: 0,
    power: 7,
    HP: 6,
    timer: 4,
    subTypes: ["JAW"],
    keywords: "Armored, Regen 8, Bribe, Defensive",
    abilities: [
      { name: "Armored" },
      { name: "Regen", amount: 8 },
      { name: "Bribe" },
      { name: "Defensive" }
    ],
    description: "Dominance ➔ Gain 4 Bits",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 412,
    category: "ENTITY" as Category,
    name: "Embedding",
    rezCost: 1,
    soul: 0,
    ash: 4,
    power: 1,
    HP: 2,
    timer: 1,
    subTypes: ["JAW"],
    keywords: "Rapture, Duplicate 2, Hollow, Lifeless, Defensive",
    abilities: [
      { name: "Rapture" },
      { name: "Duplicate", amount: 2 },
      { name: "Hollow" },
      { name: "Lifeless" },
      { name: "Defensive" }
    ],
    description: "Clash ➔ Inflict 3 Lag",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 413,
    category: "ENTITY" as Category,
    name: "IceBorg",
    rezCost: 1,
    soul: 0,
    ash: 0,
    power: 1,
    HP: 4,
    timer: 2,
    subTypes: ["JAW"],
    keywords: "Dividend, Soulless, Buffer 2, Defensive",
    abilities: [
      { name: "Dividend" },
      { name: "Soulless" },
      { name: "Buffer", amount: 2 },
      { name: "Defensive" }
    ],
    description: "Clash ➔ Inflict Freeze 2 on JAWbreaker entities",
    magi: false,
    phys: false,
    tech: true,
  },
  // JAWbreaker Entities (Tech Affinity)
  {
    faction: 'gray-border',
    id: 414,
    category: "ENTITY" as Category,
    name: "Daemon",
    rezCost: 1,
    soul: 0,
    ash: 3,
    power: 2,
    HP: 5,
    timer: 2,
    subTypes: ["JAWbreaker"],
    keywords: "Dividend, Vicious, Aggro",
    abilities: [
      { name: "Dividend" },
      { name: "Vicious" },
      { name: "Aggro" }
    ],
    description: "Clash ➔ Inflict 2 Wounds",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 415,
    category: "ENTITY" as Category,
    name: "CarJack",
    rezCost: 3,
    soul: 3,
    ash: 0,
    power: 4,
    HP: 6,
    timer: 4,
    subTypes: ["JAWbreaker"],
    keywords: "Ambush 3, Duelist, Aggro",
    abilities: [
      { name: "Ambush", amount: 3 },
      { name: "Duelist" },
      { name: "Aggro" }
    ],
    description: "Action ➔ Gain 2 Charge. Clash ➔ Lose 1 Charge.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 416,
    category: "ENTITY" as Category,
    name: "Leech",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 2,
    timer: 1,
    subTypes: ["JAWbreaker"],
    keywords: "Lifeless, Aggro",
    abilities: [
      { name: "Lifeless" },
      { name: "Aggro" }
    ],
    description: "Clash ➔ Friendly entities gain 1 Boost",
    magi: false,
    phys: false,
    tech: true,
  },
  // Versatile Entity (Tech Affinity)
  {
    faction: 'gray-border',
    id: 417,
    category: "ENTITY" as Category,
    name: "Lurker",
    rezCost: 1,
    soul: 0,
    ash: 4,
    power: 2,
    HP: 3,
    timer: 4,
    subTypes: [],
    keywords: "Stealth 2, Ambush 2, Sting 2, Barricade 2",
    abilities: [
      { name: "Stealth", amount: 2 },
      { name: "Ambush", amount: 2 },
      { name: "Sting", amount: 2 },
      { name: "Barricade", amount: 2 }
    ],
    description: "Action ➔ Disconnect",
    magi: false,
    phys: false,
    tech: true,
  },
  // Phys/Magi Entity
  {
    faction: 'gray-border',
    id: 418,
    category: "ENTITY" as Category,
    name: "Mimic",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 3,
    timer: 3,
    subTypes: [],
    keywords: "Devour, Dividend, Impostor",
    abilities: [
      { name: "Devour" },
      { name: "Dividend" },
      { name: "Impostor" }
    ],
    description: "",
    magi: true,
    phys: true,
    tech: false,
  },
  // Rituals
  {
    faction: 'gray-border',
    id: 419,
    category: "RITUAL" as Category,
    name: "Overclock",
    rezCost: 2,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Gravity",
    abilities: [
      { name: "Gravity" }
    ],
    description: "Give target friendly online entity Boost 2, Charge 2, and Lifeless.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 420,
    category: "RITUAL" as Category,
    name: "Meditation",
    rezCost: 3,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [],
    description: "Gain 3 Actions and draw 3 cards. You cannot attack this turn.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 421,
    category: "RITUAL" as Category,
    name: "Bloodletting",
    rezCost: 5,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Vicious",
    abilities: [
      { name: "Vicious" }
    ],
    description: "+10 Bits and +2 Ash. Inflict 1 Wound.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 422,
    category: "RITUAL" as Category,
    name: "Extortion",
    rezCost: 2,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Devious 2",
    abilities: [
      { name: "Devious", amount: 2 }
    ],
    description: "Gain 1 Bit for each entity.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 423,
    category: "RITUAL" as Category,
    name: "Disintegrate",
    rezCost: 1,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Gravity",
    abilities: [
      { name: "Gravity" }
    ],
    description: "Deal 4 damage to target Online enemy JAW or JAWbreaker",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 424,
    category: "RITUAL" as Category,
    name: "Amnesia",
    rezCost: 3,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [],
    description: "Inflict 2 Burden. Magical or Physical entities gain Freeze 2.",
    magi: true,
    phys: true,
    tech: false,
  },
  // Snips
  {
    faction: 'gray-border',
    id: 425,
    category: "SNIP" as Category,
    name: "Sigil",
    rezCost: 2,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Drift, Vicious",
    abilities: [
      { name: "Drift" },
      { name: "Vicious" }
    ],
    description: "Interface ➔ inflict 4 Overload",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 426,
    category: "SNIP" as Category,
    name: "Satellite Array",
    rezCost: 4,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Gravity, Locality",
    abilities: [
      { name: "Gravity" },
      { name: "Locality" }
    ],
    description: "Action ➔ Target friendly Online entity gains +1/+1 and Charge.",
    magi: false,
    phys: true,
    tech: true,
  },
  // Locations
  {
    faction: 'gray-border',
    id: 427,
    category: "LOCATION" as Category,
    name: "Obelisk",
    rezCost: 5,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 6,
    timer: 0,
    subTypes: [],
    keywords: "Horrific",
    abilities: [
      { name: "Horrific" }
    ],
    description: "2 Actions ➔ Gain Dividend 3.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 428,
    category: "LOCATION" as Category,
    name: "Warp Gate",
    rezCost: 3,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 2,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [],
    description: "Once Per Turn: Action ➔ Target entity gains Boost 2 and Stealth.",
    magi: false,
    phys: true,
    tech: true,
  },
  // Landmarks
  {
    faction: 'gray-border',
    id: 429,
    category: "LANDMARK" as Category,
    name: "Haunted Forest",
    rezCost: 0,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 4,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [],
    description: "Dominance: Inflict 2 Burden.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 430,
    category: "LANDMARK" as Category,
    name: "Museum",
    rezCost: 0,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 3,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [],
    description: "3 Actions, Sacrifice ➔ Gain 12 Bits.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 431,
    category: "LANDMARK" as Category,
    name: "Embassy",
    rezCost: 0,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 4,
    timer: 0,
    subTypes: [],
    keywords: "Dividend 3",
    abilities: [
      { name: "Dividend", amount: 3 }
    ],
    description: "You cannot attack.",
    magi: false,
    phys: true,
    tech: true,
  },
  // Syms
  {
    faction: 'gray-border',
    id: 432,
    category: "SYM" as Category,
    name: "Past Life",
    rezCost: 0,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Glitchy, Horrific",
    abilities: [
      { name: "Glitchy" },
      { name: "Horrific" }
    ],
    description: "Ascended: Beginning of Turn ➔ +1 Fate.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 433,
    category: "SYM" as Category,
    name: "Launch Codes",
    rezCost: 0,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [],
    description: "Ascend ➔ Deal 4 damage to all entities and locations.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 434,
    category: "SYM" as Category,
    name: "Causality",
    rezCost: 0,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [],
    description: "Ascended ➔ Drift, Dividend, Tarot.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 435,
    category: "ENTITY" as Category,
    name: "Dreamer",
    rezCost: 1,
    soul: 0,
    ash: 0,
    power: 1,
    HP: 1,
    timer: 1,
    subTypes: [],
    keywords: "",
    abilities: [],
    description: "",
    magi: true,
    phys: true,
    tech: true,
  },
];

// Card Registry - Single source of truth for all cards by faction
export const cardRegistry = {
  green: greenBinder,
  orange: orangeCardList,
  purple: purpleBinder,
  gray: grayBinder
};

// Helper functions to get cards
export function getCardById(faction: keyof typeof cardRegistry, id: number): Card | undefined {
  const factionCards = cardRegistry[faction] as Card[];
  return factionCards.find((card: Card) => card.id === id);
}

export function getAllCards(): Card[] {
  return [
    ...cardRegistry.green,
    ...cardRegistry.orange, 
    ...cardRegistry.purple,
    ...cardRegistry.gray
  ] as Card[];
}

export function getCardsByFaction(faction: keyof typeof cardRegistry): Card[] {
  return cardRegistry[faction] as Card[];
}
