import { Card, Category } from './cards';
import { orangeCardList } from './orangeBinder';
import purpleBinder from './purpleBinder';

// Green faction cards (Source of Truth from greenCardsNew.txt)
const greenBinder: Card[] = [
  // Tech Entities
  {
    faction: 'green-border',
    id: 1,
    category: "ENTITY" as Category,
    name: "PingWin",
    rezCost: 1,
    soul: 1,
    ash: 0,
    subTypes: ["JAW"],
    power: 1,
    HP: 4,
    timer: 3,
    keywords: "Solo, Devious. Defensive.",
    solo: 1,
    abilities: [
      { name: "ClashInflictFreezeOnOpponent", amount: 3 },
    ],
    description: "Clash ➔ Inflict 3 Freeze on target entity",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 2,
    category: "ENTITY" as Category,
    name: "ScriptKitty",
    rezCost: 2,
    soul: 2,
    ash: 0,
    subTypes: ["JAW"],
    power: 3,
    HP: 2,
    timer: 2,
    keywords: "Duplicate, Stealth 2, Pounce. Defensive.",
    stealth: 2,
    pounce: 1,
    abilities: [
      { name: "Duplicate" },
      { name: "BitPaymentGainBoostAndWound", bitCost: 1, boostAmount: 1, woundAmount: 1 },
    ],
    description: "1 Bit ➔ Gain 1 Boost and 1 Wound",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 3,
    category: "ENTITY" as Category,
    name: "PryOn",
    rezCost: 2,
    soul: 1,
    ash: 0,
    subTypes: ["JAW"],
    power: 1,
    HP: 2,
    timer: 2,
    keywords: "Deathless, Acidic. Hollow, Defensive. Cursed.",
    deathless: 1,
    abilities: [
      { name: "Cursed" },
    ],
    description: "Action, Sacrifice ➔ Gain control of target Decaying entity this turn",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 4,
    category: "ENTITY" as Category,
    name: "Hexapod",
    rezCost: 1,
    soul: 0,
    ash: 3,
    subTypes: ["JAW"],
    power: 2,
    HP: 3,
    timer: 2,
    keywords: "Acidic, Rotten, Covenant. Defensive.",
    abilities: [
      { name: "Rotten" },
      { name: "ToxicClashInflictWounds", toxicRequirement: 1, amount: 2 },
    ],
    description: "Toxic 1: Clash ➔ Inflict 2 Wounds",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 5,
    category: "ENTITY" as Category,
    name: "Ram",
    rezCost: 1,
    soul: 0,
    ash: 2,
    subTypes: ["JAW"],
    power: 2,
    HP: 2,
    timer: 2,
    keywords: "Cosmic. Locality, Hollow, Defensive.",
    abilities: [
      { name: "ClashDevelopFriendlyNonEntity", amount: 2 },
    ],
    description: "Exhaust/ Clash ➔ Target friendly Sym or Snip gains Develop 2.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 6,
    category: "ENTITY" as Category,
    name: "GrimRar",
    rezCost: 2,
    soul: 3,
    ash: 0,
    subTypes: ["JAW"],
    power: 5,
    HP: 5,
    timer: 1,
    keywords: "Rapture. Plague 3, Defensive.",
    abilities: [
      { name: "Rapture" },
      { name: "Plague", amount: 3 },
      { name: "DominanceSearchAndDrawCard", cardName: "Ram" },
    ],
    description: "Dominance/ Destiny ➔ Place and activate a [Ram].",
    magi: false,
    phys: false,
    tech: true,
  },

  // Magi Entities
  {
    faction: 'green-border',
    id: 7,
    category: "ENTITY" as Category,
    name: "Lich Queen",
    rezCost: 2,
    soul: 0,
    ash: 5,
    subTypes: [],
    power: 4,
    HP: 5,
    timer: 4,
    keywords: "Rapture, Enchanted, Deathless, Stealth. Plague 2, Cursed 2.",
    deathless: 1,
    stealth: 1,
    abilities: [
      { name: "Rapture" },
      { name: "Plague", amount: 2 },
      { name: "Cursed" },
    ],
    description: "Dominance ➔ Return 3 cards in your Limbo to HeadSpace.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 8,
    category: "ENTITY" as Category,
    name: "Priestess",
    rezCost: 2,
    soul: 1,
    ash: 0,
    subTypes: [],
    power: 2,
    HP: 2,
    timer: 2,
    keywords: "Stealth, Enchanted. Plague 3.",
    stealth: 1,
    abilities: [
      { name: "Plague", amount: 3 },
      { name: "ToxicClashFriendliesGainDecayAndHealth", toxicRequirement: 3, decayAmount: 1, hpAmount: 4 },
    ],
    description: "Toxic 3: Clash ➔ Friendly online entities gain 1 Decay and +4 Health",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 9,
    category: "ENTITY" as Category,
    name: "Lamia",
    rezCost: 2,
    soul: 2,
    ash: 0,
    subTypes: [],
    power: 2,
    HP: 3,
    timer: 2,
    keywords: "Acidic, Charge. Plague 1.",
    abilities: [
      { name: "Plague", amount: 1 },
      { name: "DestinyInflictDecayOnEnemies", maxUses: 2, amount: 2 },
    ],
    description: "Destiny 2 ➔ Inflict 2 Decay on Online enemy entities",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 10,
    category: "ENTITY" as Category,
    name: "Soothsayer",
    rezCost: 1,
    soul: 1,
    ash: 0,
    subTypes: [],
    power: 1,
    HP: 3,
    timer: 3,
    keywords: "Enchanted, Duelist. Plague 2, Locality.",
    abilities: [
      { name: "Duelist" },
      { name: "Plague", amount: 2 },
      { name: "QuestingGainActionsPerVenom" },
    ],
    description: "Questing ➔ Gain 1 Action for each Venom, then +1 Venom.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 11,
    category: "ENTITY" as Category,
    name: "Incubus",
    rezCost: 1,
    soul: 2,
    ash: 0,
    subTypes: [],
    power: 1,
    HP: 2,
    timer: 3,
    keywords: "Devious 2, Devour. Plague 2.",
    abilities: [
      { name: "Devour" },
      { name: "Plague", amount: 2 },
      { name: "OnActivateGainStats", powerGain: 2, hpGain: 2 },
    ],
    description: "Ascension ➔ Gain +2/+2",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 12,
    category: "ENTITY" as Category,
    name: "Harpies",
    rezCost: 1,
    soul: 3,
    ash: 0,
    subTypes: [],
    power: 3,
    HP: 6,
    timer: 2,
    keywords: "Rapture, Necrotic. Plague 6.",
    abilities: [
      { name: "Rapture" },
      { name: "Necrotic" },
      { name: "Plague", amount: 6 },
    ],
    description: "Place an entity from Limbo and Activate it.",
    magi: true,
    phys: false,
    tech: false,
  },

  // Phys/Magi Entities
  {
    faction: 'green-border',
    id: 13,
    category: "ENTITY" as Category,
    name: "Surrogate",
    rezCost: 2,
    soul: 0,
    ash: 2,
    subTypes: [],
    power: 3,
    HP: 5,
    timer: 3,
    keywords: "Deathless, Acidic, Rotten. Plague 2.",
    deathless: 1,
    abilities: [
      { name: "Rotten" },
      { name: "Plague", amount: 2 },
    ],
    description: "Your Dreamers are Duplicates.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 14,
    category: "ENTITY" as Category,
    name: "Flesh Hive",
    rezCost: 2,
    soul: 3,
    ash: 0,
    subTypes: [],
    power: 4,
    HP: 5,
    timer: 3,
    keywords: "Duplicate, Rapture, Drift. Plague 2, Defensive, Cursed 2.",
    abilities: [
      { name: "Duplicate" },
      { name: "Rapture" },
      { name: "Drift" },
      { name: "Plague", amount: 2 },
      { name: "Cursed" },
      { name: "DestinyGainFate", amount: 1 },
    ],
    description: "Destiny ➔ Gain 1 Fate and place a [Flesh Hive]",
    magi: true,
    phys: true,
    tech: false,
  },

  // Phys/Tech Entities
  {
    faction: 'green-border',
    id: 15,
    category: "ENTITY" as Category,
    name: "Husk",
    rezCost: 3,
    soul: 3,
    ash: 0,
    subTypes: [],
    power: 2,
    HP: 4,
    timer: 2,
    keywords: "Enchanted, Deathless. Plague 2, Aggro.",
    deathless: 1,
    abilities: [
      { name: "Plague", amount: 2 },
      { name: "ClashSearchAndDrawSnip" },
    ],
    description: "Clash ➔ Search Pandora, place a Snip, and give it 2 Develop.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 16,
    category: "ENTITY" as Category,
    name: "Hostess",
    rezCost: 5,
    soul: 1,
    ash: 0,
    subTypes: [],
    power: 4,
    HP: 5,
    timer: 3,
    keywords: "Devious 4, Stealth. Locality, Plague 3.",
    stealth: 1,
    abilities: [
      { name: "Plague", amount: 3 },
      { name: "DominanceDestinyTransferDecayToTarget" },
    ],
    description: "Dominance/ Destiny ➔ Transfer all friendly Decay to target entity.",
    magi: false,
    phys: true,
    tech: true,
  },

  // Magi/Tech Entities
  {
    faction: 'green-border',
    id: 17,
    category: "ENTITY" as Category,
    name: "WebCrawler",
    rezCost: 4,
    soul: 0,
    ash: 4,
    subTypes: [],
    power: 4,
    HP: 8,
    timer: 4,
    keywords: "Barricade 2, Ambush 2. Plague 2.",
    abilities: [
      { name: "Plague", amount: 2 },
    ],
    // NOTE: Plot-cost reduction is not currently implemented anywhere in the
    // codebase (no mechanic reads a per-player plot modifier), so this static
    // effect is not wired up.
    description: "Friendly Plot is reduced by 2.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 18,
    category: "ENTITY" as Category,
    name: "Terminal",
    rezCost: 3,
    soul: 1,
    ash: 0,
    subTypes: [],
    power: 1,
    HP: 6,
    timer: 1,
    keywords: "Covenant, Plague 2. Skav, Gravity.",
    abilities: [
      { name: "Plague", amount: 2 },
      { name: "OnActivateGainBits", amount: 3 },
    ],
    description: "Ascension ➔ +3 Bits.",
    magi: true,
    phys: false,
    tech: true,
  },

  // Phys Entity
  {
    faction: 'green-border',
    id: 19,
    category: "ENTITY" as Category,
    name: "Remnant",
    rezCost: 2,
    soul: 2,
    ash: 0,
    subTypes: [],
    power: 3,
    HP: 6,
    timer: 3,
    keywords: "Duplicate, Acidic, Inspire. Plague 3.",
    abilities: [
      { name: "Duplicate" },
      { name: "Plague", amount: 3 },
    ],
    // NOTE: No shared attack-eligibility filter exists in the attack-target
    // selection code (player and enemy attack flows are separate and have no
    // common chokepoint), so this static restriction is not enforced.
    description: "Decaying entities cannot attack you.",
    magi: false,
    phys: true,
    tech: false,
  },

  // Rituals
  {
    faction: 'green-border',
    id: 20,
    category: "RITUAL" as Category,
    name: "Hunger",
    rezCost: 2,
    soul: 0,
    ash: 0,
    keywords: "Duplicate.",
    abilities: [
      { name: "Duplicate" },
      { name: "QuestMutationRitual" },
    ],
    description: "Perform a Quest. If successful, target Decaying online entity undergoes Mutation.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 21,
    category: "RITUAL" as Category,
    name: "Code Injection",
    rezCost: 2,
    soul: 0,
    ash: 0,
    keywords: "Temptation 1.",
    abilities: [
      { name: "AllEntitiesGainDecay", amount: 1 },
    ],
    description: "All entities gain 1 Decay. Return a card from Limbo to HeadSpace.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 22,
    category: "RITUAL" as Category,
    name: "Altered State",
    rezCost: 3,
    soul: 0,
    ash: 0,
    keywords: "Temptation 1.",
    abilities: [
      { name: "GainLagAndFateOnNextAscendOrQuest", lagAmount: 2, fateAmount: 2 },
    ],
    description: "Gain 2 Lag. When you Ascend or Quest successfully this turn, +2 Fate.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 23,
    category: "RITUAL" as Category,
    name: "Containment Breach",
    rezCost: 1,
    soul: 0,
    ash: 0,
    keywords: "Locality, Cursed.",
    abilities: [
      { name: "AllEntitiesGainDecay", amount: 3 },
      { name: "Cursed" },
    ],
    description: "Give Decay 3 to all entities.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 24,
    category: "RITUAL" as Category,
    name: "Oblivion",
    rezCost: 3,
    soul: 0,
    ash: 0,
    keywords: "Temptation 2.",
    abilities: [
      { name: "OblivionEffect" },
    ],
    description: "Lose all Burden and Overload, Discard all cards in your HeadSpace, and Disconnect all entities.",
    magi: true,
    phys: false,
    tech: false,
  },

  // Locations
  {
    faction: 'green-border',
    id: 25,
    category: "LOCATION" as Category,
    name: "Isolation Chamber",
    rezCost: 2,
    soul: 0,
    ash: 0,
    HP: 2,
    keywords: "Gravity.",
    abilities: [
      { name: "MaintainGainVenom", amount: 2 },
    ],
    description: "Maintain ➔ Gain 2 Venom. Action, Sacrifice ➔ Gain 1 Fate for each Venom.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 26,
    category: "LOCATION" as Category,
    name: "Research Facility",
    rezCost: 2,
    soul: 0,
    ash: 0,
    HP: 3,
    keywords: "Dividend, Tarot. Cursed.",
    abilities: [
      { name: "Dividend" },
      { name: "Cursed" },
      { name: "DominanceMutateFriendlyEntity" },
    ],
    description: "Dominance/ Destiny ➔ Target friendly online entity undergoes Mutation.",
    magi: false,
    phys: true,
    tech: true,
  },

  // Snips
  {
    faction: 'green-border',
    id: 27,
    category: "SNIP" as Category,
    name: "Drug Trial",
    rezCost: 1,
    soul: 0,
    ash: 0,
    scrap: 4,
    keywords: "Scheme 2: Sacrifice ➔ Give 1 Decay to enemy entities and gain 10 Bits.",
    abilities: [
      { name: "SacrificeDecayEnemiesAndGainBits", decayAmount: 1, bitAmount: 10 },
    ],
    description: "",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 28,
    category: "SNIP" as Category,
    name: "Exposure Therapy",
    rezCost: 2,
    soul: 0,
    ash: 0,
    scrap: 1,
    keywords: "Interface ➔ inflict 3 Burden. Scheme 3: Action ➔ Friendly online entities gain 2 Vengeance and 1 Decay.",
    abilities: [
      { name: "ActionGainVengeanceAndDecayToFriendlies", actionCost: 1, vengeanceAmount: 2, decayAmount: 1 },
    ],
    description: "",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 29,
    category: "SNIP" as Category,
    name: "HoloGen",
    rezCost: 2,
    soul: 0,
    ash: 0,
    scrap: 2,
    keywords: "Dividend.",
    abilities: [
      { name: "Dividend" },
      { name: "ActionSearchAndDrawSubtype", actionCost: 1, subType: "JAW" },
    ],
    description: "Action ➔ Search Pandora for a JAW entity and draw it.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 30,
    category: "SNIP" as Category,
    name: "Organ Market",
    rezCost: 1,
    soul: 0,
    ash: 0,
    scrap: 3,
    keywords: "Rotten. Cursed.",
    abilities: [
      { name: "Rotten" },
      { name: "Cursed" },
      { name: "DeathGainVenom" },
      { name: "MaintainGainBitsPerVenom" },
    ],
    description: "When a decaying entity dies, +1 Venom. Maintenance ➔ +1 Bit for each Venom.",
    magi: false,
    phys: true,
    tech: false,
  },

  // Landmarks
  {
    faction: 'green-border',
    id: 31,
    category: "LANDMARK" as Category,
    name: "Fever Dream",
    rezCost: 2,
    soul: 0,
    ash: 0,
    HP: 2,
    runes: 3,
    plot: 4,
    keywords: "Rotten. Glitchy.",
    abilities: [
      { name: "Rotten" },
      { name: "Glitchy" },
      { name: "ManualDestroyDecayingEntity", actionCost: 2 },
    ],
    description: "Decay is Painless. 2 Actions ➔ Destroy target Decaying entity.",
    magi: true,
    phys: false,
    tech: false,
  },

  // Syms
  {
    faction: 'green-border',
    id: 32,
    category: "SYM" as Category,
    name: "Apotheosis",
    runes: 2,
    plot: 3,
    keywords: "Toxic 2: Action ➔ Gain 2 Wounds and 5 Bits",
    abilities: [
      { name: "ToxicActionGainWoundsAndBits", actionCost: 1, toxicRequirement: 2, woundAmount: 2, bitAmount: 5 },
    ],
    description: "",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 33,
    category: "SYM" as Category,
    name: "Inoculation",
    runes: 1,
    plot: 2,
    keywords: "Dominance ➔ Gain 1 Venom, then inflict 1 Wound for each Venom.",
    abilities: [
      { name: "DominanceGainVenomAndWounds" },
    ],
    description: "",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'green-border',
    id: 34,
    category: "SYM" as Category,
    name: "Eclipse",
    runes: 3,
    plot: 4,
    keywords: "Ascend ➔ +3 Actions. You cannot attack this turn.",
    abilities: [
      { name: "AscendGainActionsCannotAttack", amount: 3 },
    ],
    description: "",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'green-border',
    id: 35,
    category: "SYM" as Category,
    name: "Coronation",
    runes: 4,
    plot: 5,
    keywords: "Ascend ➔ Gain control of target Decaying entity and give it +5/+5.",
    abilities: [
      { name: "AscendBuffDecayingEnemyEntity" },
    ],
    description: "",
    magi: true,
    phys: false,
    tech: true,
  },
];

// Gray faction cards (from grayCardsNew.txt)
const grayBinder: Card[] = [
  // Magi Entities
  {
    faction: 'gray-border',
    id: 401,
    category: "ENTITY" as Category,
    name: "Magician",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 3,
    timer: 3,
    subTypes: [],
    keywords: "Dividend, Duplicate, Stealth 2",
    abilities: [
      { name: "Dividend" },
      { name: "Duplicate" },
      { name: "Stealth", amount: 2 }
    ],
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 402,
    category: "ENTITY" as Category,
    name: "Cryptid",
    rezCost: 2,
    soul: 2,
    ash: 0,
    power: 5,
    HP: 4,
    timer: 4,
    subTypes: [],
    keywords: "Charge 2, Devour, Override, Necrotic 2",
    abilities: [
      { name: "Charge", amount: 2 },
      { name: "Devour" },
      { name: "Override" },
      { name: "Necrotic", amount: 2 }
    ],
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 403,
    category: "ENTITY" as Category,
    name: "Familiar",
    rezCost: 1,
    soul: 0,
    ash: 1,
    power: 0,
    HP: 1,
    timer: 1,
    subTypes: [],
    keywords: "Vengeance 3, Pounce",
    abilities: [
      { name: "Vengeance", amount: 3 },
      { name: "Pounce" }
    ],
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 404,
    category: "ENTITY" as Category,
    name: "Banshee",
    rezCost: 2,
    soul: 3,
    ash: 0,
    power: 3,
    HP: 4,
    timer: 3,
    subTypes: [],
    keywords: "Stealth, Soulless, Horrific, Defensive",
    abilities: [
      { name: "Stealth" },
      { name: "Soulless" },
      { name: "Horrific" },
      { name: "Defensive" }
    ],
    description: "Dominance ➔ Gain control of target exhausted Online entity. (Note: control transfer is not currently implemented.)",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 405,
    category: "ENTITY" as Category,
    name: "Phoenix",
    rezCost: 1,
    soul: 0,
    ash: 5,
    power: 3,
    HP: 3,
    timer: 2,
    subTypes: [],
    keywords: "Charge, Deathless, Locality",
    abilities: [
      { name: "Charge" },
      { name: "Deathless" },
      { name: "Locality" },
      { name: "OnPlayDamageAllEntities", amount: 2 }
    ],
    description: "Deal 2 Damage to all Entities",
    magi: true,
    phys: false,
    tech: false,
  },
  // Physical Entities
  {
    faction: 'gray-border',
    id: 406,
    category: "ENTITY" as Category,
    name: "Dingo",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 2,
    timer: 2,
    subTypes: [],
    keywords: "Pounce, Charge, Ambush",
    abilities: [
      { name: "Pounce" },
      { name: "Charge" },
      { name: "Ambush" }
    ],
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 407,
    category: "ENTITY" as Category,
    name: "Conscripts",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 6,
    timer: 3,
    subTypes: [],
    keywords: "Barricade, Defensive",
    abilities: [
      { name: "Defensive" },
      { name: "ExhaustGrantBarricade", amount: 3 }
    ],
    description: "Exhaust ➔ Barricade 3",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 408,
    category: "ENTITY" as Category,
    name: "Artillery",
    rezCost: 4,
    soul: 2,
    ash: 0,
    power: 4,
    HP: 3,
    timer: 3,
    subTypes: [],
    keywords: "Sting 4, Ambush 2, Aggressive, Locality",
    abilities: [
      { name: "Sting", amount: 4 },
      { name: "Ambush", amount: 2 },
      { name: "Aggressive" },
      { name: "Locality" }
    ],
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 409,
    category: "ENTITY" as Category,
    name: "Firing Squad",
    rezCost: 2,
    soul: 3,
    ash: 0,
    power: 3,
    HP: 2,
    timer: 3,
    subTypes: [],
    keywords: "Duelist, Charge 2, Pounce, Duplicate 2, Aggro",
    abilities: [
      { name: "Duelist" },
      { name: "Charge", amount: 2 },
      { name: "Pounce" },
      { name: "Duplicate", amount: 2 },
      { name: "Aggro" }
    ],
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 410,
    category: "ENTITY" as Category,
    name: "Combat Medic",
    rezCost: 1,
    soul: 0,
    ash: 2,
    power: 2,
    HP: 4,
    timer: 2,
    subTypes: [],
    keywords: "Stealth, Locality, Defensive",
    abilities: [
      { name: "Stealth" },
      { name: "Locality" },
      { name: "Defensive" },
      { name: "OnPlayGrantHealthAndCharge", hpGain: 6, requiresTarget: true }
    ],
    description: "Target entity gains +6 Health and Charge.",
    magi: false,
    phys: true,
    tech: false,
  },
  // JAW Entities (Tech Affinity)
  {
    faction: 'gray-border',
    id: 411,
    category: "ENTITY" as Category,
    name: "Troll",
    rezCost: 3,
    soul: 2,
    ash: 0,
    power: 7,
    HP: 6,
    timer: 4,
    subTypes: ["JAW"],
    keywords: "Armored, Regen 8, Bribe, Defensive",
    abilities: [
      { name: "Armored" },
      { name: "Regen", amount: 8 },
      { name: "Bribe" },
      { name: "Defensive" },
      { name: "DominanceGainBits", amount: 4 }
    ],
    description: "Dominance ➔ Gain 4 Bits",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 412,
    category: "ENTITY" as Category,
    name: "Embedding",
    rezCost: 1,
    soul: 0,
    ash: 4,
    power: 1,
    HP: 2,
    timer: 1,
    subTypes: ["JAW"],
    keywords: "Rapture, Duplicate 2, Hollow, Lifeless, Defensive",
    abilities: [
      { name: "Rapture" },
      { name: "Duplicate", amount: 2 },
      { name: "Hollow" },
      { name: "Lifeless" },
      { name: "Defensive" },
      { name: "ClashInflictLag", amount: 3 }
    ],
    description: "Clash ➔ Inflict 3 Lag",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 413,
    category: "ENTITY" as Category,
    name: "IceBorg",
    rezCost: 1,
    soul: 0,
    ash: 0,
    power: 1,
    HP: 4,
    timer: 2,
    subTypes: ["JAW"],
    keywords: "Dividend, Soulless, Buffer 2, Defensive",
    abilities: [
      { name: "Dividend" },
      { name: "Soulless" },
      { name: "Buffer", amount: 2 },
      { name: "Defensive" },
      { name: "ClashInflictFreezeOnJAWbreakers", amount: 2 }
    ],
    description: "Clash ➔ Inflict Freeze 2 on JAWbreaker entities",
    magi: false,
    phys: false,
    tech: true,
  },
  // JAWbreaker Entities (Tech Affinity)
  {
    faction: 'gray-border',
    id: 414,
    category: "ENTITY" as Category,
    name: "Daemon",
    rezCost: 1,
    soul: 0,
    ash: 3,
    power: 2,
    HP: 5,
    timer: 2,
    subTypes: ["JAWbreaker"],
    keywords: "Dividend, Vicious, Aggro",
    abilities: [
      { name: "Dividend" },
      { name: "Vicious" },
      { name: "Aggro" },
      { name: "ClashInflictWounds", amount: 2 }
    ],
    description: "Clash ➔ Inflict 2 Wounds",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 415,
    category: "ENTITY" as Category,
    name: "CarJack",
    rezCost: 3,
    soul: 3,
    ash: 0,
    power: 4,
    HP: 6,
    timer: 4,
    subTypes: ["JAWbreaker"],
    keywords: "Ambush 3, Duelist, Aggro",
    abilities: [
      { name: "Ambush", amount: 3 },
      { name: "Duelist" },
      { name: "Aggro" },
      { name: "ActionGainCharge", actionCost: 1, amount: 2 },
      { name: "ClashLoseCharge", amount: 1 }
    ],
    description: "Action ➔ Gain 2 Charge. Clash ➔ Lose 1 Charge.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 416,
    category: "ENTITY" as Category,
    name: "Leech",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 2,
    timer: 1,
    subTypes: ["JAWbreaker"],
    keywords: "Lifeless, Aggro",
    abilities: [
      { name: "Lifeless" },
      { name: "Aggro" },
      { name: "ClashGrantFriendliesBoost", amount: 1 }
    ],
    description: "Clash ➔ Friendly entities gain 1 Boost",
    magi: false,
    phys: false,
    tech: true,
  },
  // Versatile Entity (Tech Affinity)
  {
    faction: 'gray-border',
    id: 417,
    category: "ENTITY" as Category,
    name: "Lurker",
    rezCost: 1,
    soul: 0,
    ash: 4,
    power: 2,
    HP: 3,
    timer: 4,
    subTypes: [],
    keywords: "Stealth 2, Ambush 2, Sting 2, Barricade 2",
    abilities: [
      { name: "Stealth", amount: 2 },
      { name: "Ambush", amount: 2 },
      { name: "Sting", amount: 2 },
      { name: "Barricade", amount: 2 },
      { name: "ActionDisconnectSelf", actionCost: 1 }
    ],
    description: "Action ➔ Disconnect",
    magi: false,
    phys: false,
    tech: true,
  },
  // Phys/Magi Entity
  {
    faction: 'gray-border',
    id: 418,
    category: "ENTITY" as Category,
    name: "Mimic",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 3,
    timer: 3,
    subTypes: [],
    keywords: "Devour, Dividend, Impostor",
    abilities: [
      { name: "Devour" },
      { name: "Dividend" },
      { name: "Impostor" }
    ],
    description: "",
    magi: true,
    phys: true,
    tech: false,
  },
  // Rituals
  {
    faction: 'gray-border',
    id: 419,
    category: "RITUAL" as Category,
    name: "Overclock",
    rezCost: 2,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Gravity",
    abilities: [
      { name: "Gravity" },
      { name: "OnPlayGrantBoostChargeLifeless", boostAmount: 2, chargeAmount: 2, requiresTarget: true }
    ],
    description: "Give target friendly online entity Boost 2, Charge 2, and Lifeless.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 420,
    category: "RITUAL" as Category,
    name: "Meditation",
    rezCost: 3,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [
      { name: "OnPlayGainActionsAndDraw", actionAmount: 3, drawAmount: 3 }
    ],
    description: "Gain 3 Actions and draw 3 cards. You cannot attack this turn.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 421,
    category: "RITUAL" as Category,
    name: "Bloodletting",
    rezCost: 5,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Vicious",
    abilities: [
      { name: "OnPlayGainBitsAshAndWound", bitAmount: 10, ashAmount: 2, woundAmount: 1 }
    ],
    description: "+10 Bits and +2 Ash. Inflict 1 Wound.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 422,
    category: "RITUAL" as Category,
    name: "Extortion",
    rezCost: 2,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Devious 2",
    abilities: [
      { name: "Devious", amount: 2 },
      { name: "Extortion" }
    ],
    description: "Gain 1 Bit for each entity.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 423,
    category: "RITUAL" as Category,
    name: "Disintegrate",
    rezCost: 1,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Gravity",
    abilities: [
      { name: "Gravity" },
      { name: "OnPlayDamageTargetSubtype", amount: 4, requiresTarget: true }
    ],
    description: "Deal 4 damage to target Online enemy JAW or JAWbreaker",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 424,
    category: "RITUAL" as Category,
    name: "Amnesia",
    rezCost: 3,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [
      { name: "OnPlayInflictBurdenAndFreezeByAffinity", burdenAmount: 2, freezeAmount: 2 }
    ],
    description: "Inflict 2 Burden. Magical or Physical entities gain Freeze 2.",
    magi: true,
    phys: true,
    tech: false,
  },
  // Snips
  {
    faction: 'gray-border',
    id: 425,
    category: "SNIP" as Category,
    name: "Sigil",
    rezCost: 2,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Drift, Vicious",
    abilities: [
      { name: "Drift" },
      { name: "Vicious" },
      { name: "InterfaceInflictOverload", amount: 4 }
    ],
    description: "Interface ➔ inflict 4 Overload",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 426,
    category: "SNIP" as Category,
    name: "Satellite Array",
    rezCost: 4,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Gravity, Locality",
    abilities: [
      { name: "Gravity" },
      { name: "Locality" },
      { name: "ActionGrantStatsAndCharge", actionCost: 1, requiresTarget: true }
    ],
    description: "Action ➔ Target friendly Online entity gains +1/+1 and Charge.",
    magi: false,
    phys: true,
    tech: true,
  },
  // Locations
  {
    faction: 'gray-border',
    id: 427,
    category: "LOCATION" as Category,
    name: "Obelisk",
    rezCost: 5,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 6,
    timer: 0,
    subTypes: [],
    keywords: "Horrific",
    abilities: [
      { name: "Horrific" },
      { name: "ActionGainDividendBonus", actionCost: 2, amount: 3 }
    ],
    description: "2 Actions ➔ Gain Dividend 3.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 428,
    category: "LOCATION" as Category,
    name: "Warp Gate",
    rezCost: 3,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 2,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [
      { name: "OncePerTurnActionGrantBoostAndStealth", actionCost: 1, boostAmount: 2, requiresTarget: true }
    ],
    description: "Once Per Turn: Action ➔ Target entity gains Boost 2 and Stealth.",
    magi: false,
    phys: true,
    tech: true,
  },
  // Landmarks
  {
    faction: 'gray-border',
    id: 429,
    category: "LANDMARK" as Category,
    name: "Haunted Forest",
    rezCost: 0,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 4,
    timer: 0,
    subTypes: [],
    runes: 2,
    plot: 3,
    keywords: "",
    abilities: [
      { name: "DominanceInflictBurden", amount: 2 }
    ],
    description: "Dominance: Inflict 2 Burden.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 430,
    category: "LANDMARK" as Category,
    name: "Museum",
    rezCost: 0,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 3,
    timer: 0,
    subTypes: [],
    runes: 2,
    plot: 4,
    keywords: "",
    abilities: [
      { name: "ManualSacrificeGainBits", actionCost: 3, amount: 12 }
    ],
    description: "3 Actions, Sacrifice ➔ Gain 12 Bits.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 431,
    category: "LANDMARK" as Category,
    name: "Embassy",
    rezCost: 0,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 4,
    timer: 0,
    subTypes: [],
    runes: 1,
    plot: 3,
    keywords: "Dividend 3",
    abilities: [
      { name: "Dividend", amount: 3 }
    ],
    description: "You cannot attack.",
    magi: false,
    phys: true,
    tech: true,
  },
  // Syms
  {
    faction: 'gray-border',
    id: 432,
    category: "SYM" as Category,
    name: "Past Life",
    rezCost: 0,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "Glitchy, Horrific",
    abilities: [
      { name: "Glitchy" },
      { name: "Horrific" },
      { name: "AscendedGainFateOnTurnStart", amount: 1 }
    ],
    description: "Ascended: Beginning of Turn ➔ +1 Fate.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 433,
    category: "SYM" as Category,
    name: "Launch Codes",
    rezCost: 0,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [
      { name: "AscendDamageAllEntitiesAndLocations", amount: 4 }
    ],
    description: "Ascend ➔ Deal 4 damage to all entities and locations.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 434,
    category: "SYM" as Category,
    name: "Causality",
    rezCost: 0,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [
      { name: "AscendedGrantKeywords" }
    ],
    description: "Ascended ➔ Drift, Dividend, Tarot.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 435,
    category: "ENTITY" as Category,
    name: "Dreamer",
    rezCost: 1,
    soul: 0,
    ash: 0,
    power: 1,
    HP: 1,
    timer: 1,
    subTypes: [],
    keywords: "",
    abilities: [],
    description: "",
    magi: true,
    phys: true,
    tech: true,
  },
];

// Card Registry - Single source of truth for all cards by faction
export const cardRegistry = {
  green: greenBinder,
  orange: orangeCardList,
  purple: purpleBinder,
  gray: grayBinder
};

// Helper functions to get cards
export function getCardById(faction: keyof typeof cardRegistry, id: number): Card | undefined {
  const factionCards = cardRegistry[faction] as Card[];
  return factionCards.find((card: Card) => card.id === id);
}

export function getAllCards(): Card[] {
  return [
    ...cardRegistry.green,
    ...cardRegistry.orange, 
    ...cardRegistry.purple,
    ...cardRegistry.gray
  ] as Card[];
}

export function getCardsByFaction(faction: keyof typeof cardRegistry): Card[] {
  return cardRegistry[faction] as Card[];
}
