import { Card } from './cards';

// Orange Faction Card Binder - Source of Truth from OrangeCardsNew.txt
// All cards use 'orange-border' faction

const orangeBinder: Card[] = [
  // Tech Entities
  {
    faction: 'orange-border',
    id: 100,
    category: "ENTITY",
    name: "TerraBite",
    rezCost: 3,
    soul: 1,
    ash: 0,
    power: 3,
    HP: 3,
    timer: 2,
    subTypes: ["JAWbreaker"],
    keywords: "Surgical, Ambush, Devour. Scav, Aggro.",
    abilities: [
      { name: "Sabotage", effectType: "wounds", amount: 3 }
    ],
    description: "Sabotage ➔ Inflict 3 Wounds",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 101,
    category: "ENTITY",
    name: "GooTooth",
    rezCost: 2,
    soul: 3,
    ash: 0,
    power: 1,
    HP: 7,
    timer: 1,
    subTypes: ["JAWbreaker"],
    keywords: "Override, Devour. Buffer 3, Hardline, Aggro.",
    abilities: [
      { name: "ActionGainVengeanceAndWound", vengeanceAmount: 2, woundAmount: 1 }
    ],
    description: "Action ➔ Gain 2 Vengeance and 1 Wound.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 102,
    category: "ENTITY",
    name: "MouseByte",
    rezCost: 1,
    soul: 0,
    ash: 2,
    power: 1,
    HP: 1,
    timer: 1,
    subTypes: ["JAWbreaker"],
    keywords: "Drift, Sting. Hardline, Locality, Aggro.",
    abilities: [
      { name: "ExhaustTargetJAWFreeze", freezeAmount: 1 }
    ],
    description: "Exhaust ➔ Target JAW gains 1 Freeze.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 103,
    category: "ENTITY",
    name: "VyperDrive",
    rezCost: 1,
    soul: 2,
    ash: 0,
    power: 1,
    HP: 4,
    timer: 1,
    subTypes: ["JAWbreaker"],
    keywords: "Drift, Duelist. Vicious, Buffer 2, Aggro.",
    abilities: [
      { name: "MaintainGainVengeance", amount: 2 }
    ],
    description: "Maintain ➔ Gain 2 Vengeance.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 104,
    category: "ENTITY",
    name: "CatPhish",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 3,
    timer: 2,
    subTypes: ["JAWbreaker"],
    keywords: "Pounce, Tarot. Glitchy, Aggro. Aura.",
    abilities: [
      { name: "AuraAllEntitiesSurgical" }
    ],
    description: "Your entities are Surgical.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 105,
    category: "ENTITY",
    name: "SylkWorm",
    rezCost: 1,
    soul: 0,
    ash: 5,
    power: 1,
    HP: 2,
    timer: 1,
    subTypes: ["JAWbreaker"],
    keywords: "Stealth, Dividend, Cosmic 2. Buffer 2, Aggro.",
    abilities: [
      { name: "AuraEnemyEntitiesFreeze" }
    ],
    description: "Online enemy entities gain Freeze 2.",
    magi: false,
    phys: false,
    tech: true,
  },

  // Physical Entities
  {
    faction: 'orange-border',
    id: 106,
    category: "ENTITY",
    name: "Pharmacist",
    rezCost: 2,
    soul: 0,
    ash: 2,
    power: 1,
    HP: 2,
    timer: 2,
    keywords: "Inspire, Grit, Necrotic 3.",
    abilities: [
      { name: "ExhaustGrantBoostAndPounce", boostAmount: 2 }
    ],
    description: "Exhaust ➔ Target friendly Online entity gains 2 Boost and Pounce.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 107,
    category: "ENTITY",
    name: "Operator",
    rezCost: 3,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 5,
    timer: 2,
    keywords: "Sting 2, Crusade, Grit. Buffer 2.",
    abilities: [
      { name: "Sabotage", effectType: "lag", amount: 2 }
    ],
    description: "Sabotage ➔ Inflict 2 Lag",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 108,
    category: "ENTITY",
    name: "Poser",
    rezCost: 3,
    soul: 0,
    ash: 0,
    power: 2,
    HP: 2,
    timer: 3,
    keywords: "Impostor. Soulless, Glitchy.",
    abilities: [
      { name: "HackingInflictOverload", amount: 3 }
    ],
    description: "Hacking ➔ inflict 3 Overload.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 109,
    category: "ENTITY",
    name: "Recruiter",
    rezCost: 2,
    soul: 0,
    ash: 3,
    power: 2,
    HP: 3,
    timer: 3,
    keywords: "Covenant, Stealth, Grit.",
    description: "Your Dreamers are Impostors.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 110,
    category: "ENTITY",
    name: "Con Artist",
    rezCost: 2,
    soul: 1,
    ash: 0,
    power: 1,
    HP: 3,
    timer: 3,
    keywords: "Covenant, Duplicate, Dividend, Necrotic. Dominance.",
    abilities: [
      { name: "DominanceInflictOverloadAndLifeless", overloadAmount: 2 }
    ],
    description: "Dominance ➔ Inflict 2 Overload and gain Lifeless.",
    magi: false,
    phys: true,
    tech: false,
  },

  // Phys/Magi Entities
  {
    faction: 'orange-border',
    id: 111,
    category: "ENTITY",
    name: "Blood Sugar",
    rezCost: 2,
    soul: 0,
    ash: 4,
    power: 3,
    HP: 4,
    timer: 2,
    keywords: "Pounce. Vicious, Buffer 2.",
    abilities: [
      { name: "BitPaymentGainStatsAndFreeze", powerGain: 1, hpGain: 1, freezeAmount: 1, bitCost: 1 }
    ],
    description: "1 Bit ➔ Gain +1/+1 and 1 Freeze.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 112,
    category: "ENTITY",
    name: "Chronomancer",
    rezCost: 2,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 2,
    timer: 2,
    keywords: "Armored, Drift. Buffer 2, Locality. Aura.",
    abilities: [
      { name: "AuraGrantBufferToOthers", bufferAmount: 2 }
    ],
    description: "Other entities have Buffer 2.",
    magi: true,
    phys: true,
    tech: false,
  },

  // Phys/Tech Entities
  {
    faction: 'orange-border',
    id: 113,
    category: "ENTITY",
    name: "Architect",
    rezCost: 3,
    soul: 3,
    ash: 0,
    power: 4,
    HP: 6,
    timer: 3,
    keywords: "Crusade, Drift, Barricade, Grit.",
    abilities: [
      { name: "ActionDevelopPlacesAndThings", bitCost: 2, developAmount: 2 }
    ],
    description: "2 Bits, Action ➔ Friendly Places and Things gain 2 Develop",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 114,
    category: "ENTITY",
    name: "Freight Train",
    rezCost: 1,
    soul: 0,
    ash: 0,
    power: 3,
    HP: 4,
    timer: 2,
    keywords: "Dividend. Buffer 3, Soulless, Defensive.",
    abilities: [
      { name: "ExhaustGrantBoostToAllies", bitCost: 1, boostAmount: 1 }
    ],
    description: "1 Bit, Exhaust ➔ Friendly entities gain 1 Boost.",
    magi: false,
    phys: true,
    tech: true,
  },

  // Magi/Tech Entities
  {
    faction: 'orange-border',
    id: 115,
    category: "ENTITY",
    name: "Z0MBI",
    rezCost: 2,
    soul: 2,
    ash: 0,
    power: 3,
    HP: 5,
    timer: 2,
    keywords: "Grit. Buffer 2, Hardline. Venom.",
    abilities: [
      { name: "HackingVenomFreeze" }
    ],
    description: "Hacking ➔ Inflict Freeze equal to Venom on enemy entities, then +1 Venom",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 117,
    category: "ENTITY",
    name: "Dread",
    rezCost: 3,
    soul: 2,
    ash: 0,
    power: 2,
    HP: 5,
    timer: 2,
    keywords: "Grit. Buffer 3, Hardline.",
    abilities: [
      { name: "DominanceInflictOverload", amount: 3 },
      { name: "SurrenderGainOverload", amount: 3 }
    ],
    description: "Dominance ➔ Inflict 3 Overload. Surrender ➔ Gain 3 Overload",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 116,
    category: "ENTITY",
    name: "Nova Kane",
    rezCost: 2,
    soul: 0,
    ash: 7,
    power: 1,
    HP: 4,
    timer: 3,
    keywords: "Solo, Stealth, Grit. Skav.",
    abilities: [
      { name: "BitPaymentGainBoost", boostAmount: 1, bitCost: 1 }
    ],
    description: "1 Bit ➔ Gain 1 Boost",
    magi: true,
    phys: false,
    tech: true,
  },

  // Locations
  {
    faction: 'orange-border',
    id: 118,
    category: "LOCATION",
    name: "Memory Leak",
    rezCost: 1,
    soul: 0,
    ash: 0,
    HP: 2,
    keywords: "Lifeless.",
    abilities: [
      { name: "BitPaymentGainActionAndWound", actionAmount: 1, woundAmount: 1, bitCost: 1 }
    ],
    description: "1 Bit ➔ Gain 1 Action and 1 Wound.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 119,
    category: "LOCATION",
    name: "Insurgency",
    rezCost: 3,
    soul: 0,
    ash: 0,
    HP: 4,
    keywords: "Dividend, Grit. Locality.",
    abilities: [
      { name: "ActionDamagePlaceAndGainAsh", actionCost: 2, damageAmount: 2, ashAmount: 2 }
    ],
    description: "2 Actions ➔ Deal 2 Damage to target Place and gain 2 Ash.",
    magi: true,
    phys: true,
    tech: false,
  },

  // Snips
  {
    faction: 'orange-border',
    id: 120,
    category: "SNIP",
    name: "Precognition",
    rezCost: 2,
    soul: 0,
    ash: 0,
    scrap: 5,
    keywords: "Surgical.",
    description: "Scheme 2: The first time you Interface Pandora each turn gain 2 Actions.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 121,
    category: "SNIP",
    name: "Quantum Stabilizer",
    rezCost: 2,
    soul: 0,
    ash: 0,
    scrap: 3,
    keywords: "Dividend.",
    description: "When you Interface Pandora, Interface 1 additional card.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 122,
    category: "SNIP",
    name: "Data Bomb",
    rezCost: 2,
    soul: 0,
    ash: 0,
    scrap: 1,
    keywords: "Duplicate 2, Surgical.",
    description: "Interface: Inflict 2 Overload for each Development. Scheme 2: Sacrifice ➔ Target entity gains Freeze 5.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 123,
    category: "SNIP",
    name: "Imitation Game",
    rezCost: 1,
    soul: 0,
    ash: 0,
    scrap: 2,
    keywords: "Dividend 2. Impostor.",
    description: "",
    magi: false,
    phys: false,
    tech: true,
  },

  // Rituals
  {
    faction: 'orange-border',
    id: 124,
    category: "RITUAL",
    name: "Brain Freeze",
    rezCost: 1,
    soul: 0,
    ash: 0,
    keywords: "",
    description: "Perform a Hack on HeadSpace. If successful, give all entities Freeze 3 and inflict 2 Overload.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 125,
    category: "RITUAL",
    name: "Stolen Briefcase",
    rezCost: 1,
    soul: 0,
    ash: 0,
    keywords: "Vicious 2",
    description: "Gain 5 Bits and 5 Ash.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 126,
    category: "RITUAL",
    name: "Dead Drop",
    rezCost: 4,
    soul: 0,
    ash: 0,
    keywords: "Duplicate.",
    description: "If you Interfaced HeadSpace this turn, +8 bits and place an enemy Adrenochrome IRL.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 127,
    category: "RITUAL",
    name: "Multi Threading",
    rezCost: 2,
    soul: 0,
    ash: 0,
    keywords: "Duplicate 2. Vicious 2.",
    description: "Perform a Hack on HeadSpace. If succesful, Interface +2 cards and gain 2 Actions.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 128,
    category: "RITUAL",
    name: "Exploit",
    rezCost: 2,
    soul: 0,
    ash: 0,
    keywords: "Surgical.",
    description: "Hacker: give target friendly online JAWbreaker +1/+1, Stealth, and Charge.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 129,
    category: "RITUAL",
    name: "Implants",
    rezCost: 2,
    soul: 0,
    ash: 0,
    keywords: "Vicious",
    description: "+4 Surge and +4 Ash. Search Pandora and draw a JAWbreaker.",
    magi: true,
    phys: true,
    tech: false,
  },

  // Syms
  {
    faction: 'orange-border',
    id: 130,
    category: "SYM",
    name: "Adrenochrome",
    runes: 2,
    plot: 2,
    keywords: "",
    description: "Ascend ➔ Gain 4 Actions, 3 Ash, and 2 Wounds.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 131,
    category: "SYM",
    name: "Cat Cafe",
    runes: 1,
    plot: 3,
    keywords: "Glitchy.",
    description: "Ascended: Beginning of Turn ➔ Inflict 1 Lag.",
    magi: false,
    phys: true,
    tech: true,
  },

  // Landmarks
  {
    faction: 'orange-border',
    id: 132,
    category: "LANDMARK",
    name: "Wasteland",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 3,
    runes: 2,
    plot: 2,
    keywords: "Grit.",
    description: "Interface, Departed ➔ Inflict 1 Wound.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 133,
    category: "LANDMARK",
    name: "Forgotten Island",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 3,
    runes: 4,
    plot: 5,
    keywords: "Dividend.",
    description: "",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 134,
    category: "LANDMARK",
    name: "Splinter Faction",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 4,
    runes: 3,
    plot: 4,
    keywords: "Grit.",
    description: "Ascend ➔ Deal 2 damage to enemy entities.",
    magi: false,
    phys: true,
    tech: true,
  },
];

export const orangeCardList: Card[] = orangeBinder;

// Helper to get a card by ID
export function getOrangeCardById(id: number): Card | undefined {
  return orangeBinder.find(card => card.id === id);
}

// Helper to get cards by category
export function getOrangeCardsByCategory(category: string): Card[] {
  return orangeBinder.filter(card => card.category === category);
}
