const purpleBinder = [
  // Physical Entities
  {
    faction: 'purple-border',
    id: 200,
    category: "ENTITY",
    name: "Dryad",
    rezCost: 2,
    soul: 2,
    ash: 0,
    power: 5,
    HP: 6,
    timer: 4,
    keywords: "Ambush 3, Inspire, Covenant. Defensive",
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 201,
    category: "ENTITY",
    name: "Viceroy",
    rezCost: 2,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 2,
    timer: 3,
    keywords: "Inspire, Dividend. Locality.",
    abilities: [
      { name: "ManualGrantOverride", requiresTarget: true }
    ],
    description: "Target friendly Online entity gains Override.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 202,
    category: "ENTITY",
    name: "Sarcophagus",
    rezCost: 1,
    soul: 0,
    ash: 2,
    power: 0,
    HP: 3,
    timer: 4,
    keywords: "Deathless, Wrath 5, Barricade. Horrific.",
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 203,
    category: "ENTITY",
    name: "Sovereign",
    rezCost: 5,
    soul: 0,
    ash: 4,
    power: 5,
    HP: 3,
    timer: 5,
    keywords: "Armored 3, Dividend 2, Crusade, Karmic.",
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 204,
    category: "ENTITY",
    name: "Gladiator",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 2,
    timer: 3,
    keywords: "Fortify, Solo, Duelist. Bribe",
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },

  // Magic Entities
  {
    faction: 'purple-border',
    id: 205,
    category: "ENTITY",
    name: "Archivist",
    rezCost: 2,
    soul: 1,
    ash: 0,
    power: 1,
    HP: 2,
    timer: 3,
    keywords: "Stealth 2, Enchanted, Harmony.",
    abilities: [
      { name: "SearchPandoraDrawRitual" }
    ],
    description: "Raiding ➔ Search Pandora and draw a Ritual.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 206,
    category: "ENTITY",
    name: "Baroness",
    rezCost: 3,
    soul: 3,
    ash: 0,
    power: 3,
    HP: 5,
    timer: 3,
    keywords: "Devour, Enchanted, Regen 5. Bribe",
    abilities: [
      { name: "DominanceClashInflictWounds", woundAmount: 3 }
    ],
    description: "Clash/ Dominance ➔ Inflict 3 Wounds.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 207,
    category: "ENTITY",
    name: "Oracle",
    rezCost: 2,
    soul: 0,
    ash: 2,
    power: 0,
    HP: 2,
    timer: 2,
    keywords: "Cosmic 2, Wrath 4. Horrific.",
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 208,
    category: "ENTITY",
    name: "Mortician",
    rezCost: 1,
    soul: 2,
    ash: 0,
    power: 0,
    HP: 3,
    timer: 3,
    keywords: "Tarot, Devour. Bribe, Locality.",
    abilities: [
      { name: "ExhaustDestroyAllOtherEntities" }
    ],
    description: "Exhaust ➔ Destroy all other entities.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 209,
    category: "ENTITY",
    name: "Demiurge",
    rezCost: 4,
    soul: 4,
    ash: 0,
    power: 1,
    HP: 8,
    timer: 6,
    keywords: "Karmic, Override, Deathless. Horrific 3.",
    abilities: [
      { name: "TriggeredSacrificeGainBoostVengeance", boostAmount: 2, vengeanceAmount: 2 }
    ],
    description: "When an entity is sacrificed: +2 Boost, +2 Vengeance",
    magi: true,
    phys: false,
    tech: false,
  },

  // Phys/Magi Entities
  {
    faction: 'purple-border',
    id: 210,
    category: "ENTITY",
    name: "Acolyte",
    rezCost: 1,
    soul: 0,
    ash: 5,
    power: 1,
    HP: 3,
    timer: 4,
    keywords: "Covenant, Cosmic, Enchanted. Horrific.",
    abilities: [
      { name: "SearchPandoraDrawLocation" }
    ],
    description: "Search Pandora and draw a Location.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 211,
    category: "ENTITY",
    name: "Pyromancer",
    rezCost: 2,
    soul: 1,
    ash: 0,
    power: 0,
    HP: 2,
    timer: 2,
    keywords: "Sting 2, Wrath 2, Deathless. Vicious, Locality",
    description: "",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 212,
    category: "ENTITY",
    name: "Poltergeist",
    rezCost: 1,
    soul: 2,
    ash: 0,
    power: 3,
    HP: 2,
    timer: 1,
    keywords: "Duelist, Deathless, Devour. Lifeless, Soulless, Horrific 2.",
    description: "",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 213,
    category: "ENTITY",
    name: "False Prophet",
    rezCost: 1,
    soul: 0,
    ash: 3,
    power: 1,
    HP: 5,
    timer: 2,
    keywords: "Horrific, Bribe.",
    abilities: [
      { name: "ExhaustActivateOfflineEntity", boostAmount: 2, requiresTarget: true }
    ],
    description: "Exhaust ➔ Activate target friendly Offline entity, it gains Boost 2 and Lifeless.",
    magi: true,
    phys: true,
    tech: false,
  },

  // Phys/Tech Entities
  {
    faction: 'purple-border',
    id: 214,
    category: "ENTITY",
    name: "Merchant Guild",
    rezCost: 1,
    soul: 3,
    ash: 0,
    power: 0,
    HP: 3,
    timer: 3,
    keywords: "Inspire, Tarot, Wrath 3, Dividend 3.",
    abilities: [
      { name: "AuraFriendlyEntitiesBribe" }
    ],
    description: "Online friendly entities have Bribe.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'purple-border',
    id: 215,
    category: "ENTITY",
    name: "Automaton",
    rezCost: 2,
    soul: 2,
    ash: 0,
    power: 3,
    HP: 5,
    timer: 3,
    keywords: "Armored, Duplicate, Sting 3. Horrific, Soulless",
    description: "",
    magi: false,
    phys: true,
    tech: true,
  },

  // Magi/Tech Entities
  {
    faction: 'purple-border',
    id: 216,
    category: "ENTITY",
    name: "Archon",
    rezCost: 4,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 4,
    timer: 2,
    keywords: "Duelist, Regen 6, Harmony. Locality.",
    abilities: [
      { name: "BitPaymentGrantVengeanceBlocked", bitCost: 2, vengeanceAmount: 2, requiresTarget: true }
    ],
    description: "2 Bits ➔ Target friendly blocked entity gains 2 Vengeance.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'purple-border',
    id: 217,
    category: "ENTITY",
    name: "Technopagan",
    rezCost: 1,
    soul: 1,
    ash: 0,
    power: 1,
    HP: 2,
    timer: 2,
    keywords: "Fortify, Cosmic 2, Harmony. Defensive",
    description: "",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'purple-border',
    id: 218,
    category: "ENTITY",
    name: "RATs",
    rezCost: 2,
    soul: 3,
    ash: 0,
    power: 1,
    HP: 3,
    timer: 2,
    keywords: "Deathless. Defensive.",
    abilities: [
      { name: "ClashExhaustDiscardEnemyHeadSpace", discardAmount: 2 }
    ],
    description: "Clash/ Exhaust ➔ Discard 2 cards at random from enemy HeadSpace.",
    magi: false,
    phys: false,
    tech: true,
  },

  // Locations
  {
    faction: 'purple-border',
    id: 219,
    category: "LOCATION",
    name: "Tyranny",
    rezCost: 2,
    soul: 0,
    ash: 0,
    HP: 2,
    keywords: "Dividend 2. Horrific.",
    abilities: [
      { name: "SurrenderGainWounds", amount: 2 }
    ],
    description: "Surrender: Gain 2 Wounds.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 220,
    category: "LOCATION",
    name: "Lighthouse",
    rezCost: 5,
    soul: 0,
    ash: 0,
    HP: 4,
    keywords: "Crusade, Harmony.",
    abilities: [
      { name: "ActionGrantVengeanceAndBoost", actionCost: 1, vengeanceAmount: 1, boostAmount: 2, requiresTarget: true }
    ],
    description: "Vengeance is Eternal. Action ➔ Give a friendly Online entity Vengeance and 2 Boost.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 221,
    category: "LOCATION",
    name: "Alchemy Lab",
    rezCost: 3,
    soul: 0,
    ash: 0,
    HP: 2,
    keywords: "",
    abilities: [
      { name: "OncePerTurnActionGrantStatsAndFreeze", actionCost: 1, powerGain: 2, hpGain: 2, freezeAmount: 1, requiresTarget: true }
    ],
    description: "Once Per Turn: Action ➔ Target Online entity gains +2/+2, Devour, and 1 Freeze.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'purple-border',
    id: 222,
    category: "LOCATION",
    name: "Reliquary",
    rezCost: 1,
    soul: 0,
    ash: 0,
    HP: 2,
    keywords: "Tarot, Harmony.",
    abilities: [
      { name: "BitActionActivateOfflineJAW", bitCost: 3, actionCost: 1, requiresTarget: true }
    ],
    description: "3 Bits, Action ➔ Activate Target Offline JAW or JAWbreaker entity.",
    magi: true,
    phys: true,
    tech: false,
  },

  // Snips
  {
    faction: 'purple-border',
    id: 223,
    category: "SNIP",
    name: "Apocrypha",
    rezCost: 2,
    soul: 0,
    ash: 0,
    scrap: 1,
    scheming: true,
    schemeThreshold: 2,
    keywords: "Duplicate, Karmic. Horrific.",
    abilities: [
      { name: "SchemeSacrificeGrantVengeanceAndLifeless", schemeThreshold: 2, vengeanceAmount: 4 }
    ],
    description: "Scheme 2: Sacrifice ➔ Target Online entity gains 4 Vengeance and Lifeless.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'purple-border',
    id: 224,
    category: "SNIP",
    name: "Entropy",
    rezCost: 2,
    soul: 0,
    ash: 0,
    scrap: 4,
    scheming: true,
    schemeThreshold: 3,
    keywords: "Inspire. Locality.",
    abilities: [
      { name: "SchemeActionInflictWoundsResetDevelopments", schemeThreshold: 3, actionCost: 1, woundAmount: 4 }
    ],
    description: "Scheme 3: Action ➔ Inflict 4 Wounds. Reset all Developments.",
    magi: false,
    phys: false,
    tech: true,
  },

  // Rituals
  {
    faction: 'purple-border',
    id: 225,
    category: "RITUAL",
    name: "Crystalize",
    rezCost: 1,
    soul: 0,
    ash: 0,
    keywords: "",
    abilities: [
      { name: "OnPlayGrantStatsFortifyFreeze", powerGain: 4, hpGain: 4, freezeAmount: 2, requiresTarget: true }
    ],
    description: "Target entity gains +4/+4, Fortify, and Freeze 2.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 226,
    category: "RITUAL",
    name: "Tithing",
    rezCost: 3,
    soul: 0,
    ash: 0,
    keywords: "",
    abilities: [
      { name: "OnPlayGainBitsOnAttack", bitAmount: 5 }
    ],
    description: "Gain 5 Bits whenever a player attacks this turn.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'purple-border',
    id: 227,
    category: "RITUAL",
    name: "Acceptable Losses",
    rezCost: 3,
    soul: 0,
    ash: 0,
    keywords: "Horrific",
    abilities: [
      { name: "RaiderDestroyOnlineEntity", requiresTarget: true }
    ],
    description: "Raider: destroy target Online entity.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'purple-border',
    id: 228,
    category: "RITUAL",
    name: "Seance",
    rezCost: 2,
    soul: 0,
    ash: 0,
    keywords: "Horrific, Locality",
    abilities: [
      { name: "OnPlayCreatePoltergeists", count: 3 }
    ],
    description: "Place three created [Poltergeist].",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'purple-border',
    id: 229,
    category: "RITUAL",
    name: "Ignition",
    rezCost: 1,
    soul: 0,
    ash: 0,
    keywords: "",
    abilities: [
      { name: "OnPlayGrantBoostAndDamage", boostAmount: 3, damageAmount: 2, requiresTarget: true }
    ],
    description: "Target Online entity gains Boost 3 and takes 2 Damage.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 230,
    category: "RITUAL",
    name: "Royal Decree",
    rezCost: 3,
    soul: 0,
    ash: 0,
    keywords: "Gravity.",
    abilities: [
      { name: "OnPlayActivateAndGrantVengeance", vengeanceAmount: 2, requiresTarget: true }
    ],
    description: "Activate target friendly Offline entity and give it 2 Vengeance",
    magi: false,
    phys: true,
    tech: false,
  },

  // Syms
  {
    faction: 'purple-border',
    id: 231,
    category: "SYM",
    name: "True Self",
    rezCost: 0,
    soul: 0,
    ash: 0,
    runes: 2,
    plot: 4,
    keywords: "",
    abilities: [
      { name: "InterfaceAscendInflictWounds", woundAmount: 3 }
    ],
    description: "Interface, Ascend ➔ Inflict 3 Wounds.",
    magi: true,
    phys: false,
    tech: true,
  },

  // Landmarks
  {
    faction: 'purple-border',
    id: 232,
    category: "LANDMARK",
    name: "Ancient Tomb",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 2,
    runes: 3,
    plot: 4,
    keywords: "Locality",
    abilities: [
      { name: "DepartedDamageEnemyEntities", damageAmount: 2 }
    ],
    description: "Departed ➔ Deal 2 damage to enemy entities.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 233,
    category: "LANDMARK",
    name: "Witch Hunt",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 1,
    runes: 3,
    plot: 2,
    keywords: "",
    abilities: [
      { name: "AscendSacrificeAndGainWounds", woundAmount: 2 }
    ],
    description: "Ascend ➔ Sacrifice and gain 2 Wounds",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 234,
    category: "LANDMARK",
    name: "Volcano",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 3,
    runes: 1,
    plot: 3,
    keywords: "Harmony. Locality.",
    abilities: [
      { name: "DevelopDealDamage", damageAmount: 1, requiresTarget: true }
    ],
    description: "Develop ➔ Deal 1 damage to target entity.",
    magi: true,
    phys: true,
    tech: false,
  },
];

export default purpleBinder;
