import { Card, Category, CostType, EffectType, SkillType, Trigger, Motive } from '../rules/cards';

const cardList: Card[] = [
    {
        id: 4,
        name: 'Night Mare',
        category: 'CREATURE',
        rezCost: 4,
        ash: 2,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 6,
        DEX: 0,
        HP: 5,
        timer: 3,
        text: 'blah blah blah blah blah',
        flavor: '',
    },
    {
        id: 27,
        name: 'Possesed Doll',
        category: 'CREATURE',
        rezCost: 1,
        soul: 1,
        magi: true,
        phys: false,
        tech: false,
        WIS: 7,
        STR: 0,
        DEX: 0,
        HP: 3,
        timer: 4,
        text: '',
        flavor: 'blah blah blah blah blah',
    },
    {
        id: 4,
        name: 'Night Mare',
        category: 'CREATURE',
        rezCost: 4,
        ash: 2,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 6,
        DEX: 0,
        HP: 5,
        timer: 3,
        text: '',
        flavor: 'blah blah blah blah blah',
    },
    {
        id: 27,
        name: 'Possesed Doll',
        category: 'CREATURE',
        rezCost: 1,
        soul: 1,
        magi: true,
        phys: false,
        tech: false,
        WIS: 7,
        STR: 0,
        DEX: 0,
        HP: 3,
        timer: 4,
        text: '',
        flavor: 'blah blah blah blah blah',
    },
    {
        id: 3,
        name: 'Hell Hound',
        category: 'CREATURE',
        rezCost: 2,
        soul: 1,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 4,
        DEX: 0,
        HP: 2,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 1,
        name: 'Lizardfolk',
        category: 'CREATURE',
        rezCost: 2,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 1,
        DEX: 0,
        HP: 3,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 2,
        name: 'Hydra',
        category: 'CREATURE',
        rezCost: 4,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 5,
        DEX: 0,
        HP: 6,
        timer: 4,
        text: '',
        flavor: '',
    },
    {
        id: 0,
        name: 'Lizardfolk',
        category: 'CREATURE',
        rezCost: 2,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 1,
        DEX: 0,
        HP: 3,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 5,
        name: 'Double Time',
        category: 'RITUAL',
        rezCost: 2,
        fate: 1,
        magi: true,
        phys: false,
        tech: false,
        effect2: {
            type: 'ACTION',
            amount: 2,
            side: 'FRIEND',
            motive: ['AVATAR'],
            dynamic: false
        },
        text: 'Gain two actions',
        flavor: '',
    },
    {
        id: 6,
        name: 'Black Fog',
        category: 'LOCATION',
        rezCost: 3,
        magi: true,
        phys: false,
        tech: true,
        HP: 4,
        skill: {
            triggered: true,
            trigger: 'ATTACKED',
            permanent: false,
            type: 'EFFECT',
            effect1: {
                type: 'BURDEN',
                amount: 1,
                side: 'FOE',
                motive: ['AVATAR'],
                dynamic: false
            }
        },
        text: 'When you are attacked, opponent gains 1 Burden',
        flavor: '',
    },
    {
        id: 7,
        name: 'Fetid Swamp',
        category: 'LANDMARK',
        runes: 6,
        promoCost: 4,
        magi: true,
        phys: true,
        tech: true,
        HP: 6,
        text: '',
        flavor: '',
    },
    {
        id: 8,
        name: 'Fetid Swamp',
        category: 'LANDMARK',
        runes: 6,
        promoCost: 4,
        magi: true,
        phys: true,
        tech: true,
        HP: 6,
        text: '',
        flavor: '',
    },
    {
        id: 9,
        name: 'Brain Rot',
        category: 'SNIP',
        magi: false,
        phys: false,
        tech: true,
        scrap: 0,
        skill: {
            triggered: true,
            trigger: 'ACCESS',
            permanent: false,
            type: 'EFFECT',
            effect1: {
                type: 'WOUND',
                side: 'FOE',
                motive: ['AVATAR'],
                dynamic: true,
                variable: {
                    selfTarget: true,
                    variableType: 'BOOSTS'
                }
            }
        },
        text: 'When accessed, opponent gains 2 Wounds for every Promo.',
        flavor: '',
    },
    {
        id: 10,
        name: 'Night Terrors',
        category: 'SYM',
        runes: 2,
        promoCost: 3,
        magi: true,
        phys: true,
        tech: true,
        skill: {
            triggered: true,
            trigger: 'SCORE_SELF',
            permanent: false,
            type: 'EFFECT',
            effect1: {
                type: 'DISCARD',
                amount: 3,
                side: 'FOE',
                motive: ['AVATAR'],
                dynamic: false
            }
        },
        cleanup1: {
            condition: 'SCORED',
            type: 'DRAW',
            amount: 2,
            side: 'FOE',
            motive: ['AVATAR'],
            dynamic: false
        },
        text: 'When scored, opponent discards 3 cards. End of Turn: If you scored this, opponent draws two cards.',
        flavor: '',
    },
    {
        id: 11,
        name: 'Transmute',
        category: 'RITUAL',
        rezCost: 3,
        fate: 2,
        wounds: 2,
        magi: true,
        phys: false,
        tech: false,
        effect1: {
            type: 'BITS',
            side: 'FRIEND',
            amount: 7,
            motive: ['AVATAR'],
            dynamic: false
        },
        text: 'Gain 7 Bits and 2 Wounds',
        flavor: '',
    },
    {
        id: 12,
        name: 'Malice',
        category: 'CREATURE',
        rezCost: 2,
        soul: 2,
        keywords: ['POUNCE'],
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 3,
        DEX: 0,
        HP: 5,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 13,
        name: 'Level One',
        category: 'SYM',
        runes: 5,
        promoCost: 5,
        magi: true,
        phys: true,
        tech: true,
        text: '',
        flavor: '',
    },
    {
        id: 14,
        name: 'Hackathon',
        category: 'LANDMARK',
        runes: 1,
        promoCost: 3,
        magi: true,
        phys: true,
        tech: true,
        HP: 2,
        skill: {
            triggered: true,
            trigger: 'BOOST_SELF',
            permanent: false,
            type: 'EFFECT',
            effect1: {
                type: 'FUMBLE',
                amount: 1,
                side: 'FOE',
                motive: ['AVATAR'],
                dynamic: false
            }
        },
        text: 'When you Boost this, opponent Fumbles 1',
        flavor: '',
    },
    {
        id: 15,
        name: 'Black Fog',
        category: 'LOCATION',
        rezCost: 3,
        magi: true,
        phys: false,
        tech: true,
        HP: 4,
        skill: {
            triggered: true,
            trigger: 'ATTACKED',
            permanent: false,
            type: 'EFFECT',
            effect1: {
                type: 'BURDEN',
                amount: 1,
                side: 'FOE',
                motive: ['AVATAR'],
                dynamic: false
            }
        },
        text: 'When you are attacked, opponent gains 1 Burden',
        flavor: '',
    },
    {
        id: 16,
        name: 'Mining Laser',
        category: 'SNIP',
        rezCost: 3,
        magi: false,
        phys: false,
        tech: true,
        scrap: 2,
        effect1: {
            actions: 2,
            type: 'DAMAGE',
            amount: 1,
            side: 'FOE',
            motive: ['CREATURE', 'LANDMARK', 'LOCATION'],
            dynamic: false
        },
        text: '2 Actions: Gain 3 Bits, Deal 1 damage to target Location, Landmark, or Creature',
        flavor: '',
    },
    {
        id: 17,
        name: 'Mining Laser',
        category: 'SNIP',
        rezCost: 3,
        magi: false,
        phys: false,
        tech: true,
        scrap: 2,
        effect1: {
            actions: 2,
            type: 'DAMAGE',
            amount: 1,
            side: 'FOE',
            motive: ['CREATURE', 'LANDMARK', 'LOCATION'],
            dynamic: false
        },
        text: '2 Actions: Gain 3 Bits, Deal 1 damage to target Location, Landmark, or Creature',
        flavor: '',
    },
    {
        id: 18,
        name: 'Pirate Ship',
        category: 'LOCATION',
        rezCost: 3,
        magi: false,
        phys: true,
        tech: false,
        HP: 3,
        cleanup1: {
            condition: 'PLAYER_ATK',
            type: 'RUNE',
            amount: 1,
            side: 'FRIEND',
            motive: ['AVATAR'],
            dynamic: false
        },
        cleanup2: {
            condition: 'PLAYER_ATK',
            type: 'BITS',
            amount: 2,
            side: 'FRIEND',
            motive: ['AVATAR'],
            dynamic: false
        },
        text: 'End of Turn: Gain 1 Fate and 2 Bits if you attacked.',
        flavor: '',
    },
    {
        id: 19,
        name: 'Hell Hound',
        category: 'CREATURE',
        rezCost: 2,
        soul: 1,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 4,
        DEX: 0,
        HP: 2,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 20,
        name: 'Golden Idol',
        category: 'LOCATION',
        rezCost: 2,
        magi: true,
        phys: false,
        tech: false,
        HP: 2,
        upkeep: {
            type: 'BITS',
            amount: 1,
            side: 'FRIEND',
            motive: ['AVATAR'],
            dynamic: false
        },
        text: 'Start of Turn: Gain 1 Bit.',
        flavor: '',
    },
    {
        id: 21,
        name: 'Golden Idol',
        category: 'LOCATION',
        rezCost: 2,
        magi: true,
        phys: false,
        tech: false,
        HP: 2,
        upkeep: {
            type: 'BITS',
            amount: 1,
            side: 'FRIEND',
            motive: ['AVATAR'],
            dynamic: false
        },
        text: 'Start of Turn: Gain 1 Bit.',
        flavor: '',
    },
    {
        id: 22,
        name: 'Golden Idol',
        category: 'LOCATION',
        rezCost: 2,
        magi: true,
        phys: false,
        tech: false,
        HP: 2,
        upkeep: {
            type: 'BITS',
            amount: 1,
            side: 'FRIEND',
            motive: ['AVATAR'],
            dynamic: false
        },
        text: 'Start of Turn: Gain 1 Bit.',
        flavor: '',
    },
    {
        id: 23,
        name: 'Curious Acolyte',
        category: 'CREATURE',
        rezCost: 3,
        magi: true,
        phys: false,
        tech: false,
        WIS: 3,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 24,
        name: 'Curious Acolyte',
        category: 'CREATURE',
        rezCost: 3,
        magi: true,
        phys: false,
        tech: false,
        WIS: 3,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 25,
        name: 'Haunting Siren',
        category: 'CREATURE',
        rezCost: 1,
        ash: 4,
        magi: true,
        phys: false,
        tech: false,
        WIS: 6,
        STR: 0,
        DEX: 0,
        HP: 8,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 26,
        name: 'Haunting Siren',
        category: 'CREATURE',
        rezCost: 1,
        ash: 4,
        magi: true,
        phys: false,
        tech: false,
        WIS: 6,
        STR: 0,
        DEX: 0,
        HP: 8,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 28,
        name: 'Martyrdom',
        category: 'RITUAL',
        rezCost: 4,
        fate: 1,
        magi: true,
        phys: false,
        tech: false,
        effect1: {
            type: 'DESTROY',
            side: 'FOE',
            motive: ['CREATURE'],
            dynamic: false
        },
        text: 'Destroy target enemy creature.',
        flavor: '',
    },
    {
        id: 29,
        name: 'Transmute',
        category: 'RITUAL',
        rezCost: 3,
        fate: 2,
        wounds: 2,
        magi: true,
        phys: false,
        tech: false,
        effect1: {
            type: 'BITS',
            side: 'FRIEND',
            amount: 7,
            motive: ['AVATAR'],
            dynamic: false
        },
        text: 'Gain 7 Bits and 2 Wounds',
        flavor: '',
    }
];

// Export the array of cards
export const libraryOne: Card[] = cardList;