import { Card, Category, EffectType, SkillType, Trigger } from '../rules/cards';

const deckTwo: Card[] = [
 
{
    faction: 'orange-border',
    id: 115,
    category: "LOCATION",
    name: "Pirate Vessel",
    rezCost: 3,
    soul: 0,
    ash: 0,
    HP: 2,
    keywords: "Crusade.",
    abilities: [
      { name: "Crusade" },
      { name: "GainResourcesOnInterface" }
    ],
    description: "When you Interface HeadSpace, +2 Bits and +2 Ash.",
    magi: false,
    phys: true,
    tech: true,
},
{
    faction: 'orange-border',
    id: 116,
    category: "LOCATION",
    name: "Insurgency",
    rezCost: 2,
    soul: 0,
    ash: 0,
    HP: 3,
    keywords: "",
    abilities: [
      {
        name: "DamageTargetPlace",
        type: "manual",
        actionsRequired: 2,
        requiresExhaust: false,
        requiresTarget: true,
        effect: {
          name: "DamageTargetPlace",
          damageAmount: 1,
        },
      },
      {
        name: "GainSurgeAndAshOnPlaceDestroyed",
        type: "triggered",
        triggers: ["placeDestroyed"],
      },
    ],
    description:
      "2 Actions ➔ Deal 1 Damage to target Place. Whenever another Place is destroyed, +3 Surge and +3 Ash.",
    magi: true,
    phys: true,
    tech: false,
},
{
    faction: 'orange-border',
    id: 117, // Replace with a specific ID if needed
    category: "SNIP",
    name: "Precognition",
    rezCost: 1,
    soul: 0,
    ash: 0,
    scrap: 3,
    schemeThreshold: 2, // Scheme 2
    scheming: true,     // Indicates this card can be developed via Scheme
    abilities: [
      {
        name: "GainActionsOnPandoraInterface",
        type: "triggered",
        triggers: ["successfulHack"],
        effect: {
          amount: 3,
        },
      },
    ],
    description:
      "Scheme 2: The first time you Interface Pandora each turn gain 3 Actions.",
    magi: true,
    phys: true,
    tech: false,
},
{
    faction: 'orange-border',
    id: 118, // Replace with a specific ID if needed
    category: "SNIP",
    name: "Quantum Stabilizer",
    rezCost: 2,
    soul: 0,
    ash: 0,
    scrap: 3,
    abilities: [
      {
        name: "PandoraAccess",
        type: "static",
      },
    ],
    description: "When you Interface Pandora, Interface 1 additional card.",
    magi: true,
    phys: false,
    tech: true,
},
{
    faction: 'orange-border',
    id: 119, // Assign a unique ID if needed
    category: "SNIP",
    name: "Data Bomb",
    rezCost: 2,
    soul: 0,
    ash: 0,
    scrap: 1,
    schemeThreshold: 2, // Scheme 2
    scheming: true,
    development: 0, // Starts with 0 Developments
    abilities: [
      {
        name: "DataBombWhenInterfaced",
        type: "triggered",
        triggers: ["snipAccessed"],
        effect: {
          overloadPerDevelopment: 2,
        },
      },
      {
        name: "DataBombSacrificeForFreeze",
        type: "manual",
        requiresTarget: true,
        effect: {
          freezeAmount: 5,
        },
      },
    ],
    description:
      "When Interfaced, inflict 2 Overload for each Development. Scheme 2: Sacrifice ➔ Target entity gains Freeze 5.",
    magi: false,
    phys: true,
    tech: true,
},
{
    faction: 'orange-border',
    id: 120,
    category: "SNIP",
    name: "Imitation Game",
    rezCost: 2,
    soul: 0,
    ash: 0,
    scrap: 2,
    abilities: [
      { name: "Impostor" },
      {
        name: "ImitationGameInflictOverload",
        type: "manual",
        effect: {
          overloadAmount: 3,
        },
      },
    ],
    description: "Inflict 3 Overload.",
    magi: false,
    phys: false,
    tech: true,
},
{
    faction: 'orange-border',
    id: 121,
    category: "RITUAL",
    name: "Brain Freeze",
    rezCost: 1,
    soul: 0,
    ash: 0,
    abilities: [
      {
        name: "BrainFreezeHackPandora",
        type: "onPlay",
      },
    ],
    description: "Perform a Hack on Pandora. If successful, give all entities Freeze 3.",
    magi: true,
    phys: false,
    tech: true,
},
{
    faction: 'orange-border',
    id: 122,
    category: "RITUAL",
    name: "Stolen Briefcase",
    rezCost: 1,
    soul: 0,
    ash: 0,
    abilities: [
      { name: "Vicious", amount: 1 },
      {
        name: "GainAshAndOverload",
        type: "onPlay",
      },
    ],
    description: "Gain 6 Ash and 3 Overload.",
    magi: false,
    phys: true,
    tech: false,
},
{
    faction: 'orange-border',
    id: 123,
    category: "RITUAL",
    name: "Forgery",
    rezCost: 2,
    soul: 0,
    ash: 0,
    abilities: [
      {
        name: "ForgeryEffect",
        type: "onPlay",
      },
    ],
    description:
      "If you Interfaced HeadSpace this turn, gain 10 Bits and place a new enemy CatPhish in Underpass.",
    magi: true,
    phys: false,
    tech: true,
},
{
    faction: 'orange-border',
    id: 124,
    category: "RITUAL",
    name: "Multi Threading",
    rezCost: 1,
    soul: 0,
    ash: 0,
    abilities: [
      { name: "Duplicate", amount: 1 },
      {
        name: "MultiThreadingEffect",
        type: "onPlay",
        requiresTarget: true,
      },
    ],
    description: "Draw 2, Boost an entity, and perform a Hack.",
    magi: false,
    phys: false,
    tech: true,
},
{
    faction: 'orange-border',
    id: 125,
    category: "RITUAL",
    name: "Exploit",
    rezCost: 3,
    soul: 0,
    ash: 0,
    abilities: [
      {
        name: "ExploitEffect",
        type: "conditional",
        condition: "successfulHack",
        requiresTarget: true,
      },
    ],
    description: "If you Hacked successfully this turn, give target friendly JAWbreaker +2/+2 and Stealth.",
    magi: false,
    phys: false,
    tech: true,
},
{
    faction: 'orange-border',
    id: 126,
    category: "RITUAL",
    name: "Implants",
    rezCost: 2,
    abilities: [
      {
        name: "Vicious",
        amount: 1,
      },
      {
        name: "ImplantsEffect",
        type: "onPlay",
      }
    ],
    description: "+2 Surge and +2 Ash. Search Pandora and draw a JAWbreaker.",
    magi: false,
    phys: true,
    tech: true,
    subTypes: [],
},
{
    faction: 'orange-border',
    id: 127,
    category: "SYM",
    name: "Adrenochrome",
    runes: 2,
    plot: 2,
    abilities: [{ name: "AdrenochromeAscend" }],
    description: "Ascend ➔ Gain 2 Actions, 3 Ash, and 4 Overload.",
    magi: true,
    phys: true,
    tech: false,
    subTypes: [],
},
{
    faction: 'orange-border',
    id: 128,
    category: "SYM",
    name: "Cat Cafe",
    runes: 1,
    plot: 3,
    abilities: [{ name: "CatCafeAscended" }],
    description: "Ascended: Beginning of Turn ➔ Inflict 3 Overload.",
    magi: true,
    phys: true,
    tech: false,
    subTypes: [], // Add subTypes if applicable
},
{
    faction: 'orange-border',
    id: 129,
    category: "LANDMARK",
    name: "Wasteland",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 2,
    runes: 2,
    plot: 2,
    abilities: [{ name: "Wasteland" }],
    description: "Stolen, Destroyed ➔ Inflict 1 Wound.",
    magi: false,
    phys: true,
    tech: false,
},
{
    faction: 'orange-border',
    id: 130,
    category: "LANDMARK",
    name: "Forgotten Island",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 6,
    runes: 4,
    plot: 5,
    abilities: [{ name: "ForgottenIslandAscend" }],
    description: "Ascend ➔ +10 Bits.",
    magi: true,
    phys: true,
    tech: false,
},
{
    faction: 'orange-border',
    id: 131,
    category: "LANDMARK",
    name: "Splinter Faction",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 5,
    runes: 3,
    plot: 4,
    abilities: [{ name: "SplinterFactionAscend" }],
    description: "Ascend ➔ Deal 2 damage to enemy entities.",
    magi: false,
    phys: true,
    tech: true,
  }
];

// Export the array of cards
export const cardList1: Card[] = deckTwo;