import { Card, Category, EffectType, SkillType, Trigger } from '../rules/cards';

const deckTwo: Card[] = [ 
  {
    faction: 'orange-border',
    id: 101,
    name: "SilkWorm",
    category: "ENTITY",
    subTypes: ["JAWbreaker"],
    rezCost: 1,
    soul: 0,
    ash: 5,
    runes: 0,
    plot: 0,
    keywords: "Buffer 2, Aggressive",
    description: "Online enemy entities gain Freeze 2.",
    magi: false,
    phys: false,
    tech: true,
    power: 1,
    HP: 3,
    timer: 2,
    scrap: 0,
    abilities: [
      { name: "Buffer", amount: 2 },
      { name: "MassFreezeEnemies" },
    ],
    aggressive: true,
  },
  {
    faction: 'orange-border',
    id: 104, // Assign a unique ID
    name: "VyperDrive",
    category: "ENTITY",
    subTypes: ["JAWbreaker"],
    rezCost: 1,
    soul: 2,
    ash: 0,
    runes: 0,
    plot: 0,
    keywords: "Drift. Vicious, Aggressive.", // Used for display only
    description: "",
    magi: false,
    phys: false,
    tech: true,
    power: 1,
    HP: 4,
    timer: 2,
    scrap: 0,
    abilities: [
      { name: "Drift" },
      { name: "Vicious", amount: 1 },
    ],
    aggressive: true,
    defensive: false,
  },
  {
    faction: 'orange-border',
    id: 104, // Assign a unique ID
    name: "VyperDrive",
    category: "ENTITY",
    subTypes: ["JAWbreaker"],
    rezCost: 1,
    soul: 2,
    ash: 0,
    runes: 0,
    plot: 0,
    keywords: "Drift. Vicious, Aggressive.", // Used for display only
    description: "",
    magi: false,
    phys: false,
    tech: true,
    power: 1,
    HP: 4,
    timer: 2,
    scrap: 0,
    abilities: [
      { name: "Drift" },
      { name: "Vicious", amount: 1 },
    ],
    aggressive: true,
    defensive: false,
  },
  {
    faction: 'orange-border',
    id: 107, // Unique ID
    name: "BluTooth",
    category: "ENTITY",
    subTypes: ["JAWbreaker"],
    rezCost: 2,
    soul: 3,
    ash: 0,
    runes: 0,
    plot: 0,
    keywords: "Override. Buffer 4, Aggressive.",
    description: "2 Actions ➔ Gain Vengeance 4.",
    magi: false,
    phys: false,
    tech: true,
    power: 2,
    HP: 5,
    timer: 1,
    scrap: 0,
    abilities: [
      { name: "Buffer", amount: 4 },
      { name: "ManualAbility", actionsRequired: 2, effect: { name: "GainVengeance", amount: 4 } },
    ],
    aggressive: true,
    defensive: false,
  },
  {
    faction: 'orange-border',
    id: 100,
    category: "ENTITY",
    name: "TerraBite",
    rezCost: 4,
    soul: 1,
    ash: 0,
    subTypes: ["JAWbreaker"],
    power: 5,
    HP: 3,
    timer: 3,
    keywords: "Aggressive.",
    abilities: [
      { name: "DominanceGainCharge" },
    ],
    description: "Dominance ➔ Gain Charge.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 101,
    name: "SilkWorm",
    category: "ENTITY",
    subTypes: ["JAWbreaker"],
    rezCost: 1,
    soul: 0,
    ash: 5,
    runes: 0,
    plot: 0,
    keywords: "Buffer 2, Aggressive",
    description: "Online enemy entities gain Freeze 2.",
    magi: false,
    phys: false,
    tech: true,
    power: 1,
    HP: 3,
    timer: 2,
    scrap: 0,
    abilities: [
      { name: "Buffer", amount: 2 },
      { name: "MassFreezeEnemies" },
    ],
    aggressive: true,
  },
  {
    faction: 'orange-border',
    id: 104, // Assign a unique ID
    name: "VyperDrive",
    category: "ENTITY",
    subTypes: ["JAWbreaker"],
    rezCost: 1,
    soul: 2,
    ash: 0,
    runes: 0,
    plot: 0,
    keywords: "Drift. Vicious, Aggressive.", // Used for display only
    description: "",
    magi: false,
    phys: false,
    tech: true,
    power: 1,
    HP: 4,
    timer: 2,
    scrap: 0,
    abilities: [
      { name: "Drift" },
      { name: "Vicious", amount: 1 },
    ],
    aggressive: true,
    defensive: false,
  },
  {
    faction: 'orange-border',
    id: 105, // Unique ID
    name: "CatPhish",
    category: "ENTITY",
    subTypes: ["JAWbreaker"],
    rezCost: 2,
    soul: 1,
    ash: 0,
    runes: 0,
    plot: 0,
    keywords: "Pounce. Glitchy, Aggressive.", // For display purposes
    description: "",
    magi: false,
    phys: false,
    tech: true,
    power: 2,
    HP: 3,
    timer: 2,
    scrap: 0,
    abilities: [
      { name: "Glitchy", amount: 1 },
      { name: "Pounce", amount: 1 },
    ],
    aggressive: true,
    defensive: false,
  },
  {
    faction: 'orange-border',
    id: 107, // Unique ID
    name: "BluTooth",
    category: "ENTITY",
    subTypes: ["JAWbreaker"],
    rezCost: 2,
    soul: 3,
    ash: 0,
    runes: 0,
    plot: 0,
    keywords: "Override. Buffer 4, Aggressive.",
    description: "2 Actions ➔ Gain Vengeance 4.",
    magi: false,
    phys: false,
    tech: true,
    power: 2,
    HP: 5,
    timer: 1,
    scrap: 0,
    abilities: [
      { name: "Buffer", amount: 4 },
      { name: "ManualAbility", actionsRequired: 2, effect: { name: "GainVengeance", amount: 4 } },
    ],
    aggressive: true,
    defensive: false,
  },
  {
    faction: 'orange-border',
    id: 111,
    category: "ENTITY",
    name: "Recruiter",
    rezCost: 2,
    soul: 0,
    ash: 3,
    power: 2,
    HP: 3,
    timer: 3,
    keywords: "Stealth.",
    abilities: [
      { name: "GrantImpostorToDreamers" },
    ],
    description: "Your Dreamers are Impostors.",
    stealth: 1,
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 112,
    category: "ENTITY",
    name: "Blood Sugar",
    rezCost: 2,
    soul: 0,
    ash: 4,
    power: 3,
    HP: 6,
    timer: 2,
    keywords: "Vicious 3.",
    abilities: [
      {
        name: "Vicious",
        amount: 3,
      },
      {
        name: "OnEnterGainActions",
        actionsGained: 3,
      },
    ],
    description: "Gain 3 Actions.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 113,
    category: "ENTITY",
    name: "Frost Witch",
    rezCost: 2,
    soul: 1,
    ash: 0,
    power: 2,
    HP: 3,
    timer: 2,
    keywords: "Glitchy, Locality.",
    abilities: [
      { name: "Glitchy" },
      { name: "Locality" },
      { name: "DominanceInflictFreeze", amount: 1 },
    ],
    description: "Dominance ➔ Inflict Freeze 1 on enemy entities.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 115,
    category: "ENTITY",
    name: "Freight Train",
    rezCost: 2,
    soul: 0,
    ash: 0,
    power: 3,
    HP: 4,
    timer: 2,
    abilities: [
      { name: 'Buffer', amount: 3 },
      {
        name: "BoostAllAllies",
        actionsRequired: 0,
        requiresExhaust: true,
        requiresTarget: false,
        effect: {
          name: "BoostAllAllies",
          boostAmount: 2,
        },
      },
    ],
    soulless: true,
    locality: true,
    defensive: true,
    keywords: "Buffer 3.",
    description: "Exhaust ➔ Friendly entities gain Boost 2.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 116,
    category: "ENTITY",
    name: "Leviathan",
    rezCost: 2,
    soul: 3,
    ash: 0,
    power: 3,
    HP: 7,
    timer: 2,
    abilities: [
      { name: 'Buffer', amount: 2 },
      {
        name: 'GainVenomOnInterface',
      },
      {
        name: 'DestroyWithVenom',
        actionsRequired: 0, // No action points required
        requiresExhaust: true, // Requires exhaustion
        requiresTarget: true, // Requires a target
        effect: {
          name: 'DestroyTargetWithVenom',
        },
      },
    ],
    keywords: "Buffer 2.",
    description:
      "When you Interface HeadSpace, +3 Venom. Exhaust ➔ Destroy target Online entity with HP less than Venom.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 117,
    category: "ENTITY",
    name: "Nova Kane",
    rezCost: 2,
    soul: 0,
    ash: 7,
    power: 3,
    HP: 3,
    timer: 4,
    keywords: "Solo 2.",
    abilities: [
      {
        name: "GainStealth",
        type: "manual",
        actionsRequired: 1, // Assuming it requires 1 action to activate
        requiresExhaust: false, // Does not require exhaustion
        requiresTarget: false, // Does not require a target
        effect: {
          name: "GainStealth",
          amount: 1,
        },
      }
    ],
    description: "Action ➔ Gain Stealth.",
    solo: 2,
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 115,
    category: "LOCATION",
    name: "Pirate Vessel",
    rezCost: 3,
    soul: 0,
    ash: 0,
    HP: 2,
    keywords: "Crusade.",
    abilities: [
      { name: "Crusade" },
      { name: "GainResourcesOnInterface" }
    ],
    description: "When you Interface HeadSpace, +2 Bits and +2 Ash.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 115,
    category: "LOCATION",
    name: "Pirate Vessel",
    rezCost: 3,
    soul: 0,
    ash: 0,
    HP: 2,
    keywords: "Crusade.",
    abilities: [
      { name: "Crusade" },
      { name: "GainResourcesOnInterface" }
    ],
    description: "When you Interface HeadSpace, +2 Bits and +2 Ash.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 115,
    category: "LOCATION",
    name: "Pirate Vessel",
    rezCost: 3,
    soul: 0,
    ash: 0,
    HP: 2,
    keywords: "Crusade.",
    abilities: [
      { name: "Crusade" },
      { name: "GainResourcesOnInterface" }
    ],
    description: "When you Interface HeadSpace, +2 Bits and +2 Ash.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 117, // Replace with a specific ID if needed
    category: "SNIP",
    name: "Foresight",
    rezCost: 1,
    soul: 0,
    ash: 0,
    scrap: 3,
    schemeThreshold: 2, // Scheme 2
    scheming: true,     // Indicates this card can be developed via Scheme
    abilities: [
      {
        name: "GainActionsOnPandoraInterface",
        type: "triggered",
        triggers: ["successfulHack"],
        effect: {
          amount: 3,
        },
      },
    ],
    description:
      "Scheme 2: The first time you Interface Pandora each turn gain 3 Actions.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 118,
    category: "SNIP",
    name: "Quantum Stabilizer",
    rezCost: 2,
    soul: 0,
    ash: 0,
    scrap: 3,
    abilities: [
      {
        name: "PandoraAccess",
        type: "static",
      },
    ],
    description: "When you Interface Pandora, Interface 1 additional card.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 120,
    category: "SNIP",
    name: "Imitation Game",
    rezCost: 2,
    soul: 0,
    ash: 0,
    scrap: 2,
    abilities: [
      { name: "Impostor" },
      {
        name: "ImitationGameInflictOverload",
        type: "manual",
        effect: {
          overloadAmount: 3,
        },
      },
    ],
    description: "Inflict 3 Overload.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 122,
    category: "RITUAL",
    name: "Stolen Briefcase",
    rezCost: 1,
    soul: 0,
    ash: 0,
    abilities: [
      { name: "Vicious", amount: 1 },
      {
        name: "GainAshAndOverload",
        type: "onPlay",
      },
    ],
    description: "Gain 6 Ash and 3 Overload.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 122,
    category: "RITUAL",
    name: "Stolen Briefcase",
    rezCost: 1,
    soul: 0,
    ash: 0,
    abilities: [
      { name: "Vicious", amount: 1 },
      {
        name: "GainAshAndOverload",
        type: "onPlay",
      },
    ],
    description: "Gain 6 Ash and 3 Overload.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 123,
    category: "RITUAL",
    name: "Forgery",
    rezCost: 2,
    soul: 0,
    ash: 0,
    abilities: [
      {
        name: "ForgeryEffect",
        type: "onPlay",
      },
    ],
    description:
      "If you Interfaced HeadSpace this turn, gain 10 Bits and place a new enemy CatPhish in IRL.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 123,
    category: "RITUAL",
    name: "Forgery",
    rezCost: 2,
    soul: 0,
    ash: 0,
    abilities: [
      {
        name: "ForgeryEffect",
        type: "onPlay",
      },
    ],
    description:
      "If you Interfaced HeadSpace this turn, gain 10 Bits and place a new enemy CatPhish in IRL.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 124,
    category: "RITUAL",
    name: "Multi Threading",
    rezCost: 1,
    soul: 0,
    ash: 0,
    abilities: [
      { name: "Duplicate", amount: 1 },
      {
        name: "MultiThreadingEffect",
        type: "onPlay",
        requiresTarget: true,
      },
    ],
    description: "Draw 2, Boost an entity, and perform a Hack.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'orange-border',
    id: 127,
    category: "SYM",
    name: "Adrenochrome",
    runes: 2,
    plot: 2,
    abilities: [{ name: "AdrenochromeAscend" }],
    description: "Ascend ➔ Gain 2 Actions, 3 Ash, and 4 Overload.",
    magi: true,
    phys: true,
    tech: false,
    subTypes: [],
  },
  {
    faction: 'orange-border',
    id: 128,
    category: "SYM",
    name: "Cat Cafe",
    runes: 1,
    plot: 3,
    abilities: [{ name: "CatCafeAscended" }],
    description: "Ascended: Beginning of Turn ➔ Inflict 3 Overload.",
    magi: true,
    phys: true,
    tech: false,
    subTypes: [], // Add subTypes if applicable
  },
  {
    faction: 'orange-border',
    id: 130,
    category: "LANDMARK",
    name: "Forgotten Island",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 6,
    runes: 4,
    plot: 5,
    abilities: [{ name: "ForgottenIslandAscend" }],
    description: "Ascend ➔ +10 Bits.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 130,
    category: "LANDMARK",
    name: "Forgotten Island",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 6,
    runes: 4,
    plot: 5,
    abilities: [{ name: "ForgottenIslandAscend" }],
    description: "Ascend ➔ +10 Bits.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 130,
    category: "LANDMARK",
    name: "Forgotten Island",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 6,
    runes: 4,
    plot: 5,
    abilities: [{ name: "ForgottenIslandAscend" }],
    description: "Ascend ➔ +10 Bits.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    faction: 'orange-border',
    id: 131,
    category: "LANDMARK",
    name: "Splinter Faction",
    rezCost: 0,
    soul: 0,
    ash: 0,
    HP: 5,
    runes: 3,
    plot: 4,
    abilities: [{ name: "SplinterFactionAscend" }],
    description: "Ascend ➔ Deal 2 damage to enemy entities.",
    magi: false,
    phys: true,
    tech: true,
  },
  // gray
  {
    faction: 'gray-border',
    id: 413,
    category: "ENTITY",
    name: "Embedding",
    rezCost: 2,
    soul: 0,
    ash: 4,
    power: 2,
    HP: 2,
    timer: 1,
    subTypes: ["JAW"],
    keywords: "Rapture, Duplicate, Deathless. Defensive.",
    abilities: [
      { name: "Rapture", amount: 1 },
      { name: "Duplicate", amount: 1 },
      { name: "Deathless" },
    ],
    description: "",
    defensive: true,
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 413,
    category: "ENTITY",
    name: "Embedding",
    rezCost: 2,
    soul: 0,
    ash: 4,
    power: 2,
    HP: 2,
    timer: 1,
    subTypes: ["JAW"],
    keywords: "Rapture, Duplicate, Deathless. Defensive.",
    abilities: [
      { name: "Rapture", amount: 1 },
      { name: "Duplicate", amount: 1 },
      { name: "Deathless" },
    ],
    description: "",
    defensive: true,
    magi: false,
    phys: false,
    tech: true,
  },
  {
    faction: 'gray-border',
    id: 422,
    category: "RITUAL",
    name: "Extortion",
    rezCost: 3,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [
      {
        name: "Extortion",
        type: "onPlay",
      },
    ],
    description: "Gain 2 Bits for each entity.",
    defensive: false,
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'gray-border',
    id: 422,
    category: "RITUAL",
    name: "Extortion",
    rezCost: 3,
    soul: 0,
    ash: 0,
    power: 0,
    HP: 0,
    timer: 0,
    subTypes: [],
    keywords: "",
    abilities: [
      {
        name: "Extortion",
        type: "onPlay",
      },
    ],
    description: "Gain 2 Bits for each entity.",
    defensive: false,
    magi: false,
    phys: true,
    tech: false,
  },
  // other
  {
    faction: 'purple-border',
    id: 204,
    category: "ENTITY",
    name: "Sovereign",
    rezCost: 5,
    soul: 0,
    ash: 4,
    power: 3,
    HP: 3,
    timer: 3,
    subTypes: [],
    keywords: "Armored 4, Dividend 2, Crusade, Karmic.",
    abilities: [
      { name: "Dividend", amount: 2 },
      { name: "Crusade" },
      { name: "Karmic" },
    ],
    armored: 4,
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 210,
    category: "ENTITY",
    name: "Demiurge",
    rezCost: 6,
    soul: 4,
    ash: 0,
    power: 6,
    HP: 5,
    timer: 5,
    subTypes: [],
    keywords: "Deathless, Override, Karmic. Gravity.",
    abilities: [
      { name: "Karmic" },
      { name: "Gravity" },
    ],
    deathless: 1,
    override: 1,
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 210,
    category: "ENTITY",
    name: "Demiurge",
    rezCost: 6,
    soul: 4,
    ash: 0,
    power: 6,
    HP: 5,
    timer: 5,
    subTypes: [],
    keywords: "Deathless, Override, Karmic. Gravity.",
    abilities: [
      { name: "Karmic" },
      { name: "Gravity" },
    ],
    deathless: 1,
    override: 1,
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    faction: 'purple-border',
    id: 210,
    category: "ENTITY",
    name: "Demiurge",
    rezCost: 6,
    soul: 4,
    ash: 0,
    power: 6,
    HP: 5,
    timer: 5,
    subTypes: [],
    keywords: "Deathless, Override, Karmic. Gravity.",
    abilities: [
      { name: "Karmic" },
      { name: "Gravity" },
    ],
    deathless: 1,
    override: 1,
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
];

// Export the array of cards
export const cardList1: Card[] = deckTwo;