// import { Card, Category, EffectType, SkillType, Trigger, Motive } from '../rules/cards';

// const cardList: Card[] = [
//     // Tech Entities
//     {
//         id: 1,
//         category: "ENTITY",
//         name: "PingWin",
//         rezCost: 1,
//         soul: 1,
//         ash: 0,
//         subTypes: ["JAW"],
//         power: 1,
//         HP: 4,
//         timer: 3,
//         abilities: "Acidic, Armored. Defensive.",
//         description: "",
//         magi: false,
//         phys: false,
//         tech: true,
//         faction: 'green-border'
//     },
//     {
//         id: 2,
//         category: "ENTITY",
//         name: "Ram",
//         rezCost: 3,
//         soul: 0,
//         ash: 2,
//         subTypes: ["JAW"],
//         power: 2,
//         HP: 2,
//         timer: 2,
//         abilities: "Locality, Defensive.",
//         description: "Exhaust ➔ Target friendly Sym or Snip gains Develop 2.",
//         magi: false,
//         phys: false,
//         tech: true,
//         faction: 'green-border'
//     },
//     {
//         id: 3,
//         category: "ENTITY",
//         name: "PawPups",
//         rezCost: 1,
//         soul: 1,
//         ash: 0,
//         subTypes: ["JAW"],
//         power: 1,
//         HP: 3,
//         timer: 1,
//         abilities: "Barricade, Devious. Syndrome 2. Defensive.",
//         description: "",
//         magi: false,
//         phys: false,
//         tech: true,
//         faction: 'green-border'
//     },
//     {
//         id: 4,
//         category: "ENTITY",
//         name: "ScriptKitty",
//         rezCost: 3,
//         soul: 2,
//         ash: 0,
//         subTypes: ["JAW"],
//         power: 3,
//         HP: 2,
//         timer: 2,
//         abilities: "Stealth, Pounce, Ambush. Defensive.",
//         description: "",
//         magi: false,
//         phys: false,
//         tech: true,
//         faction: 'green-border'
//     },
//     {
//         id: 5,
//         category: "ENTITY",
//         name: "DeadHerring",
//         rezCost: 2,
//         soul: 0,
//         ash: 3,
//         subTypes: ["JAW"],
//         power: 2,
//         HP: 4,
//         timer: 3,
//         abilities: "Rotten, Deathless. Defensive.",
//         description: "",
//         magi: false,
//         phys: false,
//         tech: true,
//         faction: 'green-border'
//     },
//     {
//         id: 6,
//         category: "ENTITY",
//         name: "Bau",
//         rezCost: 3,
//         soul: 3,
//         ash: 0,
//         subTypes: ["JAW"],
//         power: 4,
//         HP: 6,
//         timer: 3,
//         abilities: "Enchanted, Dividend 3. Syndrome 3, Defensive.",
//         description: "",
//         magi: false,
//         phys: false,
//         tech: true,
//     },

//     // Magi Entities
//     {
//         id: 7,
//         category: "ENTITY",
//         name: "Lich Queen",
//         rezCost: 2,
//         soul: 0,
//         ash: 5,
//         subTypes: [],
//         power: 5,
//         HP: 10,
//         timer: 4,
//         abilities: "Deathless, Enchanted. Syndrome 3, Cursed.",
//         description: "Dominance ➔ Return 3 cards in your Limbo to HeadSpace.",
//         magi: true,
//         phys: false,
//         tech: false,
//         faction: 'green-border'
//     },
//     {
//         id: 8,
//         category: "ENTITY",
//         name: "Plague Priestess",
//         rezCost: 2,
//         soul: 1,
//         ash: 0,
//         subTypes: [],
//         power: 2,
//         HP: 3,
//         timer: 3,
//         abilities: "Stealth. Syndrome 3.",
//         description: "Target entity gains +5 HP and Decay.",
//         magi: true,
//         phys: false,
//         tech: false,
//         faction: 'green-border'
//     },
//     {
//         id: 9,
//         category: "ENTITY",
//         name: "Lamia",
//         rezCost: 4,
//         soul: 1,
//         ash: 0,
//         subTypes: [],
//         power: 2,
//         HP: 3,
//         timer: 3,
//         abilities: "Acidic. Syndrome 2.",
//         description: "Gain control of target Decaying entity and give it Freeze 1.",
//         magi: true,
//         phys: false,
//         tech: false,
//         faction: 'green-border'
//     },
//     {
//         id: 10,
//         category: "ENTITY",
//         name: "Incubus",
//         rezCost: 1,
//         soul: 2,
//         ash: 0,
//         subTypes: [],
//         power: 2,
//         HP: 4,
//         timer: 3,
//         abilities: "Exhaust ➔ Target entity gains Vengeance 3 and Decay 3.",
//         description: "",
//         magi: true,
//         phys: false,
//         tech: false,
//         faction: 'green-border'
//     },
//     {
//         id: 11,
//         category: "ENTITY",
//         name: "Harpies",
//         rezCost: 6,
//         soul: 1,
//         ash: 0,
//         subTypes: [],
//         power: 3,
//         HP: 6,
//         timer: 3,
//         abilities: "Rapture 3, Necrotic 3. Syndrome 3.",
//         description: "",
//         magi: true,
//         phys: false,
//         tech: false,
//     },

//     // Phys/Magi Entities
//     {
//         id: 12,
//         category: "ENTITY",
//         name: "Surrogate",
//         rezCost: 1,
//         soul: 0,
//         ash: 2,
//         subTypes: [],
//         power: 2,
//         HP: 5,
//         timer: 3,
//         abilities: "Acidic, Rotten. Locality, Syndrome 1.",
//         description: "Dreamers have Devious.",
//         magi: true,
//         phys: true,
//         tech: false,
//         faction: 'green-border'
//     },
//     {
//         id: 13,
//         category: "ENTITY",
//         name: "Flesh Hive",
//         rezCost: 2,
//         soul: 3,
//         ash: 0,
//         subTypes: [],
//         power: 6,
//         HP: 8,
//         timer: 4,
//         abilities: "Deathless, Devour, Charge 1. Syndrome 2, Cursed",
//         description: "Whenever a Decaying entity dies, +1 Fate and +2 Overload.",
//         magi: true,
//         phys: true,
//         tech: false,
//     },

//     // Phys/Tech Entities
//     {
//         id: 14,
//         category: "ENTITY",
//         name: "Husk",
//         rezCost: 3,
//         soul: 3,
//         ash: 0,
//         subTypes: [],
//         power: 5,
//         HP: 6,
//         timer: 4,
//         abilities: "Ambush 3, Devious. Aggressive.",
//         description: "",
//         magi: false,
//         phys: true,
//         tech: true,
//         faction: 'green-border'
//     },
//     {
//         id: 15,
//         category: "ENTITY",
//         name: "Hostess",
//         rezCost: 5,
//         soul: 1,
//         ash: 0,
//         subTypes: [],
//         power: 3,
//         HP: 2,
//         timer: 3,
//         abilities: "Stealth. Locality, Syndrome 1.",
//         description: "Transfer all friendly Decay to target entity.",
//         magi: false,
//         phys: true,
//         tech: true,
//     },

//     // Magi/Tech Entities
//     {
//         id: 16,
//         category: "ENTITY",
//         name: "WebCrawler",
//         rezCost: 4,
//         soul: 0,
//         ash: 4,
//         subTypes: [],
//         power: 4,
//         HP: 8,
//         timer: 4,
//         abilities: "Ambush 2, Barricade 2, Devour. Aggressive.",
//         description: "",
//         magi: true,
//         phys: false,
//         tech: true,
//         faction: 'green-border'
//     },
//     {
//         id: 17,
//         category: "ENTITY",
//         name: "Terminal",
//         rezCost: 3,
//         soul: 2,
//         ash: 0,
//         subTypes: [],
//         power: 3,
//         HP: 6,
//         timer: 4,
//         abilities: "Covenant, Syndrome 2. Gravity.",
//         description: "Whenever a player Ascends a card, +3 Bits.",
//         magi: true,
//         phys: false,
//         tech: true,
//     },

//     // Phys Entity
//     {
//         id: 18,
//         category: "ENTITY",
//         name: "Remnant",
//         rezCost: 2,
//         soul: 2,
//         ash: 0,
//         subTypes: [],
//         power: 4,
//         HP: 6,
//         timer: 4,
//         abilities: "Deathless, Necrotic 2. Syndrome 2.",
//         description: "",
//         magi: false,
//         phys: true,
//         tech: false,
//         faction: 'green-border'
//     }
// ];

// // Export the array of cards
// export const libraryOne: Card[] = cardList;