export const cards = [
  // Magi Entities
  {
    type: "ENTITY",
    name: "Magician",
    rezCost: 1,
    soulCost: 1,
    ashCost: 0,
    power: 2,
    health: 3,
    timer: 3,
    abilities: "Dividend, Duplicate, Stealth 2",
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Cryptid",
    rezCost: 2,
    soulCost: 2,
    ashCost: 0,
    power: 5,
    health: 4,
    timer: 4,
    abilities: "Charge 2, Devour, Override, Necrotic 2.",
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Familiar",
    rezCost: 1,
    soulCost: 0,
    ashCost: 1,
    power: 0,
    health: 1,
    timer: 1,
    abilities: "Vengeance 3, Pounce",
    description: "",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Banshee",
    rezCost: 2,
    soulCost: 3,
    ashCost: 0,
    power: 3,
    health: 4,
    timer: 3,
    abilities: "Stealth. Soulless, Horrific, Defensive",
    description: "Dominance ➔ Gain control of target exhausted Online entity.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Phoenix",
    rezCost: 1,
    soulCost: 0,
    ashCost: 5,
    power: 3,
    health: 3,
    timer: 2,
    abilities: "Charge, Deathless. Locality.",
    description: "Deal 2 Damage to all Entities",
    magi: true,
    phys: false,
    tech: false,
  },

  // Physical Entities
  {
    type: "ENTITY",
    name: "Dingo",
    rezCost: 1,
    soulCost: 1,
    ashCost: 0,
    power: 2,
    health: 2,
    timer: 2,
    abilities: "Pounce, Charge, Ambush",
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Conscripts",
    rezCost: 1,
    soulCost: 1,
    ashCost: 0,
    power: 2,
    health: 6,
    timer: 3,
    abilities: "Barricade. Defensive",
    description: "Exhaust ➔ Barricade 3",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Artillery",
    rezCost: 4,
    soulCost: 2,
    ashCost: 0,
    power: 4,
    health: 3,
    timer: 3,
    abilities: "Sting 4, Ambush 2. Agressive. Locality.",
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Firing Squad",
    rezCost: 2,
    soulCost: 3,
    ashCost: 0,
    power: 3,
    health: 2,
    timer: 3,
    abilities: "Duelist, Charge 2, Pounce, Duplicate 2. Aggro",
    description: "",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Combat Medic",
    rezCost: 1,
    soulCost: 0,
    ashCost: 2,
    power: 2,
    health: 4,
    timer: 2,
    abilities: "Stealth. Locality, Defensive",
    description: "Target entity gains +6 Health and Charge.",
    magi: false,
    phys: true,
    tech: false,
  },

  // JAW Entities (Tech Affinity)
  {
    type: "ENTITY",
    name: "Troll",
    rezCost: 3,
    soulCost: 2,
    ashCost: 0,
    power: 7,
    health: 6,
    timer: 4,
    subtype: "JAW",
    abilities: "Armored. Regen 8. Bribe, Defensive.",
    description: "Dominance ➔ Gain 4 Bits",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "ENTITY",
    name: "Embedding",
    rezCost: 1,
    soulCost: 0,
    ashCost: 4,
    power: 1,
    health: 2,
    timer: 1,
    subtype: "JAW",
    abilities: "Rapture, Duplicate 2. Hollow, Lifeless, Defensive.",
    description: "Clash ➔ Inflict 3 Lag",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "ENTITY",
    name: "IceBorg",
    rezCost: 1,
    soulCost: 0,
    ashCost: 0,
    power: 1,
    health: 4,
    timer: 2,
    subtype: "JAW",
    abilities: "Dividend. Soulless, Buffer 2, Defensive",
    description: "Clash ➔ Inflict Freeze 2 on JAWbreaker entities",
    magi: false,
    phys: false,
    tech: true,
  },

  // JAWbreaker Entities (Tech Affinity)
  {
    type: "ENTITY",
    name: "Daemon",
    rezCost: 1,
    soulCost: 0,
    ashCost: 3,
    power: 2,
    health: 5,
    timer: 2,
    subtype: "JAWbreaker",
    abilities: "Dividend. Vicious, Aggro",
    description: "Clash ➔ Inflict 2 Wounds",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "ENTITY",
    name: "CarJack",
    rezCost: 3,
    soulCost: 3,
    ashCost: 0,
    power: 4,
    health: 6,
    timer: 4,
    subtype: "JAWbreaker",
    abilities: "Ambush 3, Duelist. Aggro.",
    description: "Action ➔ Gain 2 Charge. Clash ➔ Lose 1 Charge.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "ENTITY",
    name: "Leech",
    rezCost: 1,
    soulCost: 1,
    ashCost: 0,
    power: 2,
    health: 2,
    timer: 1,
    subtype: "JAWbreaker",
    abilities: "Lifeless, Aggro.",
    description: "Clash ➔ Friendly entities gain 1 Boost",
    magi: false,
    phys: false,
    tech: true,
  },
  // Versatile Entity (Tech Affinity)
  {
    type: "ENTITY",
    name: "Lurker",
    rezCost: 1,
    soulCost: 0,
    ashCost: 4,
    power: 2,
    health: 3,
    timer: 4,
    abilities: "Stealth 2, Ambush 2, Sting 2, Barricade 2.",
    description: "Action ➔ Disconnect",
    magi: false,
    phys: false,
    tech: true,
  },

  // Phys/Magi Entity
  {
    type: "ENTITY",
    name: "Mimic",
    rezCost: 1,
    soulCost: 1,
    ashCost: 0,
    power: 2,
    health: 3,
    timer: 3,
    abilities: "Devour, Dividend, Impostor",
    description: "",
    magi: true,
    phys: true,
    tech: false,
  },

  // Rituals
  {
    type: "RITUAL",
    name: "Overclock",
    rezCost: 2,
    abilities: "Gravity.",
    description:
      "Give target friendly online entity Boost 2, Charge 2, and Lifeless.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    type: "RITUAL",
    name: "Meditation",
    rezCost: 3,
    abilities: "",
    description:
      "Gain 3 Actions and draw 3 cards. You cannot attack this turn.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    type: "RITUAL",
    name: "Bloodletting",
    rezCost: 5,
    abilities: "Vicious",
    description: "+10 Bits and +2 Ash. Inflict 1 Wound.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    type: "RITUAL",
    name: "Extortion",
    rezCost: 2,
    abilities: "Devious 2.",
    description: "Gain 1 Bit for each entity.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "RITUAL",
    name: "Disintegrate",
    rezCost: 1,
    abilities: "Gravity.",
    description: "Deal 4 damage to target Online enemy JAW or JAWbreaker",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "RITUAL",
    name: "Amnesia",
    rezCost: 3,
    abilities: "",
    description:
      "Inflict 2 Burden. Magical or Physical entities gain Freeze 2.",
    magi: true,
    phys: true,
    tech: false,
  },

  // Snips
  {
    type: "SNIP",
    name: "Sigil",
    rezCost: 2,
    scrap: 1,
    abilities: "Drift. Vicious.",
    description: "Interface ➔ inflict 4 Overload",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    type: "SNIP",
    name: "Satellite Array",
    rezCost: 4,
    scrap: 4,
    abilities: "Gravity, Locality.",
    description:
      "Action ➔ Target friendly Online entity gains +1/+1 and Charge.",
    magi: false,
    phys: true,
    tech: true,
  },

  // Locations
  {
    type: "LOCATION",
    name: "Obelisk",
    rezCost: 5,
    health: 6,
    abilities: "Horrific.",
    description: "2 Actions ➔ Gain Dividend 3.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    type: "LOCATION",
    name: "Warp Gate",
    rezCost: 3,
    health: 2,
    abilities: "",
    description:
      "Once Per Turn: Action ➔ Target entity gains Boost 2 and Stealth.",
    magi: false,
    phys: true,
    tech: true,
  },

  // Landmarks
  {
    type: "LANDMARK",
    name: "Haunted Forest",
    rezCost: 0,
    health: 4,
    runes: 2,
    plot: 3,
    abilities: "",
    description: "Dominance: Inflict 2 Burden.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    type: "LANDMARK",
    name: "Museum",
    rezCost: 0,
    health: 3,
    runes: 2,
    plot: 4,
    abilities: "",
    description: "3 Actions, Sacrifice ➔ Gain 12 Bits.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "LANDMARK",
    name: "Embassy",
    rezCost: 0,
    health: 4,
    runes: 1,
    plot: 3,
    abilities: "Dividend 3",
    description: "You cannot attack.",
    magi: false,
    phys: true,
    tech: true,
  },

  // Syms
  {
    type: "SYM",
    name: "Past Life",
    runes: 1,
    plot: 2,
    abilities: "Glitchy, Horrific.",
    description: "Ascended: Beginning of Turn ➔ +1 Fate.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    type: "SYM",
    name: "Launch Codes",
    runes: 4,
    plot: 4,
    abilities: "",
    description: "Ascend ➔ Deal 4 damage to all entities and locations.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "SYM",
    name: "Causality",
    runes: 3,
    plot: 3,
    abilities: "",
    description: "Ascended ➔ Drift, Dividend, Tarot.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Dreamer",
    rezCost: 1,
    soulCost: 0,
    ashCost: 0,
    power: 1,
    health: 1,
    timer: 1,
    abilities: "",
    description: "",
    magi: true,
    phys: true,
    tech: true,
  },
  // {
  //   type: "ENTITY",
  //   name: "ERROR",
  //   rezCost: -1,
  //   soulCost: 0,
  //   ashCost: 0,
  //   power: -1,
  //   health: -1,
  //   timer: -1,
  //   description: "",
  //   magi: false,
  //   phys: false,
  //   tech: false,
  //   anomaly: true,
  // },
];