export const cards = [
  // Tech Entities
  {
    type: "ENTITY",
    name: "TerraBite",
    rezCost: 3,
    soulCost: 1,
    ashCost: 0,
    affinities: ["Tech"],
    subtype: "JAWbreaker",
    power: 3,
    health: 3,
    timer: 2,
    abilities: "Surgical, Ambush, Devour. Scav, Aggro.",
    description: "Sabotage ➔ Inflict 3 Wounds",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "ENTITY",
    name: "GooTooth",
    rezCost: 2,
    soulCost: 3,
    ashCost: 0,
    affinities: ["Tech"],
    subtype: "JAWbreaker",
    power: 1,
    health: 7,
    timer: 1,
    abilities: "Override, Devour. Buffer 3, Hardline, Aggro.",
    description: "Action ➔ Gain 2 Vengeance and 1 Wound.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "ENTITY",
    name: "MouseByte",
    rezCost: 1,
    soulCost: 0,
    ashCost: 2,
    affinities: ["Tech"],
    subtype: "JAWbreaker",
    power: 1,
    health: 1,
    timer: 1,
    abilities: "Drift, Sting. Hardline, Locality, Aggro.",
    description: "Exhaust ➔ Target JAW gains 1 Freeze.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "ENTITY",
    name: "VyperDrive",
    rezCost: 1,
    soulCost: 2,
    ashCost: 0,
    affinities: ["Tech"],
    subtype: "JAWbreaker",
    power: 1,
    health: 4,
    timer: 1,
    abilities: "Drift, Duelist. Vicious, Buffer 2, Aggro.",
    description: "Maintain ➔ Gain 2 Vengeance.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "ENTITY",
    name: "CatPhish",
    rezCost: 1,
    soulCost: 1,
    ashCost: 0,
    affinities: ["Tech"],
    subtype: "JAWbreaker",
    power: 2,
    health: 3,
    timer: 2,
    abilities: "Pounce, Tarot. Glitchy, Aggro.",
    description: "Your entities are Surgical.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "ENTITY",
    name: "SylkWorm",
    rezCost: 1,
    soulCost: 0,
    ashCost: 5,
    affinities: ["Tech"],
    subtype: "JAWbreaker",
    power: 1,
    health: 2,
    timer: 1,
    abilities: "Stealth, Dividend, Cosmic 2. Buffer 2, Aggro.",
    description: "Online enemy entities gain Freeze 2.",
    magi: false,
    phys: false,
    tech: true,
  },

  // Physical Entities
  {
    type: "ENTITY",
    name: "Pharmacist",
    rezCost: 2,
    soulCost: 0,
    ashCost: 2,
    affinities: ["Phys"],
    power: 1,
    health: 2,
    timer: 2,
    abilities: "Inspire, Grit, Necrotic 3.",
    description:
      "Exhaust ➔ Target friendly Online entity gains 2 Boost and Pounce.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Operator",
    rezCost: 3,
    soulCost: 1,
    ashCost: 0,
    power: 2,
    health: 5,
    timer: 2,
    abilities: "Sting 2, Crusade, Grit. Buffer 2.",
    description: "Sabotage ➔ Inflict 2 Lag",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Poser",
    rezCost: 3,
    soulCost: 0,
    ashCost: 0,
    power: 2,
    health: 2,
    timer: 3,
    abilities: "Impostor. Soulless, Glitchy.",
    description: "Hacking ➔ inflict 3 Overload.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Recruiter",
    rezCost: 2,
    soulCost: 0,
    ashCost: 3,
    power: 2,
    health: 3,
    timer: 3,
    abilities: "Covenant, Stealth, Grit.",
    description: "Your Dreamers are Impostors.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Con Artist", //new
    rezCost: 2,
    soulCost: 1,
    ashCost: 0,
    affinities: ["Phys"],
    power: 1,
    health: 3,
    timer: 3,
    abilities: "Covenant, Duplicate, Dividend, Necrotic.",
    description: "Dominance ➔ Inflict 2 Overload and gain Lifeless.",
    magi: false,
    phys: true,
    tech: false,
  },

  // Phys/Magi Entities
  {
    type: "ENTITY",
    name: "Blood Sugar",
    rezCost: 2,
    soulCost: 0,
    ashCost: 4,
    affinities: ["Phys", "Magi"],
    power: 3,
    health: 4,
    timer: 2,
    abilities: "Pounce. Vicious, Buffer 2.",
    description: "1 Bit ➔ Gain +1/+1 and 1 Freeze.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    type: "ENTITY",
    name: "Chronomancer",
    rezCost: 2,
    soulCost: 1,
    ashCost: 0,
    affinities: ["Phys", "Magi"],
    power: 2,
    health: 2,
    timer: 2,
    abilities: "Armored, Drift. Buffer 2, Locality.",
    description: "Other entities have Buffer 2.",
    magi: true,
    phys: true,
    tech: false,
  },

  // Phys/Tech Entities
  {
    type: "ENTITY",
    name: "Architect",
    rezCost: 3,
    soulCost: 3,
    ashCost: 0,
    affinities: ["Phys", "Tech"],
    power: 4,
    health: 6,
    timer: 3,
    abilities: "Crusade, Drift, Barricade, Grit.",
    description: "2 Bits, Action ➔ Friendly Places and Things gain 2 Develop",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    type: "ENTITY",
    name: "Freight Train",
    rezCost: 1,
    soulCost: 0,
    ashCost: 0,
    affinities: ["Phys", "Tech"],
    subtype: "",
    power: 3,
    health: 4,
    timer: 2,
    abilities: "Dividend. Buffer 3, Soulless, Defensive.",
    description: "1 Bit, Exhaust ➔ Friendly entities gain 1 Boost.",
    magi: false,
    phys: true,
    tech: true,
  },

  // Magi/Tech Entities
  {
    type: "ENTITY",
    name: "Z0MBI",
    rezCost: 2,
    soulCost: 2,
    ashCost: 0,
    affinities: ["Magi", "Tech"],
    power: 3,
    health: 5,
    timer: 2,
    abilities: "Grit. Buffer 2, Hardline.",
    description:
      "Hacking ➔ Inflict Freeze equal to Venom on enemy entities, then +1 Venom",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    type: "ENTITY",
    name: "Nova Kane",
    rezCost: 2,
    soulCost: 0,
    ashCost: 7,
    affinities: ["Magi", "Tech"],
    power: 1,
    health: 4,
    timer: 3,
    abilities: "Solo, Stealth, Grit. Skav.",
    description: "1 Bit ➔ Gain 1 Boost",
    magi: true,
    phys: false,
    tech: true,
  },

  // Magi Entity
  {
    type: "ENTITY",
    name: "Dread",
    rezCost: 1,
    soulCost: 0,
    ashCost: 6,
    affinities: ["Magi"],
    power: 5,
    health: 3,
    timer: 2,
    abilities: "Deathless, Override. Buffer 3, Aggro.",
    description: "Dominance ➔ Inflict 3 Overload. Surrender ➔ Gain 3 Overload.",
    magi: true,
    phys: false,
    tech: false,
  },

  // Locations
  {
    type: "LOCATION",
    name: "Memory Leak",
    rezCost: 1,
    soulCost: 0,
    ashCost: 0,
    health: 2,
    affinities: ["Phys", "Tech"],
    abilities: "Lifeless.",
    description: "1 Bit ➔ Gain 1 Action and 1 Wound.",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    type: "LOCATION",
    name: "Insurgency",
    rezCost: 3,
    soulCost: 0,
    ashCost: 0,
    health: 4,
    affinities: ["Phys", "Tech"],
    abilities: "Dividend, Grit. Locality.",
    description:
      "2 Actions ➔ Deal 2 Damage to target Place and gain 2 Ash.",
    magi: true,
    phys: true,
    tech: false,
  },

  // Snips
  {
    type: "SNIP",
    name: "Precognition",
    rezCost: 2,
    soulCost: 0,
    ashCost: 0,
    scrap: 5,
    affinities: ["Magi", "Tech"],
    abilities: "Surgical.",
    description:
      "Scheme 2: The first time you Interface Pandora each turn gain 2 Actions.",
    magi: true,
    phys: false,
    tech: false,
  },
  {
    type: "SNIP",
    name: "Quantum Stabilizer",
    rezCost: 2,
    soulCost: 0,
    ashCost: 0,
    scrap: 3,
    affinities: ["Tech"],
    abilities: "Dividend.",
    description: "When you Interface Pandora, Interface 1 additional card.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    type: "SNIP",
    name: "Data Bomb",
    rezCost: 2,
    soulCost: 0,
    ashCost: 0,
    scrap: 1,
    affinities: ["Tech", "Phys"],
    abilities: "Duplicate 2, Surgical.",
    description:
      "Interface: Inflict 2 Overload for each Development. Scheme 2: Sacrifice ➔ Target entity gains Freeze 5.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    type: "SNIP",
    name: "Imitation Game",
    rezCost: 1,
    soulCost: 0,
    ashCost: 0,
    scrap: 2,
    abilities: "Dividend 2. Impostor.",
    description: "",
    magi: false,
    phys: false,
    tech: true,
  },

  // Rituals
  {
    type: "RITUAL",
    name: "Brain Freeze",
    rezCost: 1,
    soulCost: 0,
    ashCost: 0,
    affinities: ["Magi", "Tech"],
    abilities: "",
    description:
      "Perform a Hack on HeadSpace. If successful, give all entities Freeze 3 and inflict 2 Overload.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    type: "RITUAL",
    name: "Stolen Briefcase",
    rezCost: 1,
    soulCost: 0,
    ashCost: 0,
    affinities: ["Tech", "Phys"],
    abilities: "Vicious 2",
    description: "Gain 5 Bits and 5 Ash.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "RITUAL",
    name: "Dead Drop",
    rezCost: 4,
    soulCost: 0,
    ashCost: 0,
    affinities: ["Magi", "Tech"],
    abilities: "Duplicate.",
    description:
      "If you Interfaced HeadSpace this turn, +8 bits and place an enemy Adrenochrome IRL.",
    magi: true,
    phys: false,
    tech: true,
  },
  {
    type: "RITUAL",
    name: "Multi Threading",
    rezCost: 2,
    soulCost: 0,
    ashCost: 0,
    affinities: ["Tech"],
    abilities: "Duplicate 2. Vicious 2.",
    description: "Perform a Hack on HeadSpace. If succesful, Interface +2 cards and gain 2 Actions.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "RITUAL",
    name: "Exploit",
    rezCost: 2,
    soulCost: 0,
    ashCost: 0,
    affinities: ["Tech"],
    abilities: "Surgical.",
    description:
      "Hacker: give target friendly online JAWbreaker +1/+1, Stealth, and Charge.",
    magi: false,
    phys: false,
    tech: true,
  },
  {
    type: "RITUAL",
    name: "Implants",
    rezCost: 2,
    soulCost: 0,
    ashCost: 0,
    affinities: ["Phys", "Tech"],
    abilities: "Vicious",
    description: "+4 Surge and +4 Ash. Search Pandora and draw a JAWbreaker.",
    magi: true,
    phys: true,
    tech: false,
  },

  // Syms
  {
    type: "SYM",
    name: "Adrenochrome",
    runes: 2,
    plot: 2,
    affinities: ["Phys"],
    abilities: "",
    description: "Ascend ➔ Gain 4 Actions, 3 Ash, and 2 Wounds.",
    magi: false,
    phys: true,
    tech: true,
  },
  {
    type: "SYM",
    name: "Cat Cafe",
    runes: 1,
    plot: 3,
    affinities: ["Phys", "Tech"],
    abilities: "Glitchy.",
    description: "Ascended: Beginning of Turn ➔ Inflict 1 Lag.",
    magi: false,
    phys: true,
    tech: true,
  },

  // Landmarks
  {
    type: "LANDMARK",
    name: "Wasteland",
    rezCost: 0,
    soulCost: 0,
    ashCost: 0,
    health: 3,
    runes: 2,
    plot: 2,
    affinities: ["Phys"],
    abilities: "Grit.",
    description: "Interface, Departed ➔ Inflict 1 Wound.",
    magi: false,
    phys: true,
    tech: false,
  },
  {
    type: "LANDMARK",
    name: "Forgotten Island",
    rezCost: 0,
    soulCost: 0,
    ashCost: 0,
    health: 3,
    runes: 4,
    plot: 5,
    affinities: ["Magi", "Phys"],
    abilities: "Dividend.",
    description: "",
    magi: true,
    phys: true,
    tech: false,
  },
  {
    type: "LANDMARK",
    name: "Splinter Faction",
    rezCost: 0,
    soulCost: 0,
    ashCost: 0,
    health: 4,
    runes: 3,
    plot: 4,
    affinities: ["Phys", "Tech"],
    abilities: "Grit.",
    description: "Ascend ➔ Deal 2 damage to enemy entities.",
    magi: false,
    phys: true,
    tech: true,
  },
];