// import { Card, Category, CostType, EffectType, SkillType, Trigger, Motive } from '../rules/cards';

// const cardList: Card[] = [
//     {
//         id: 4,
//         name: 'tHex',
//         category: 'ENTITY',
//         subTypes: ['Verd'],
//         keywords: ['OVERRIDE', 'DEVOUR'],
//         rezCost: 4,
//         ash: 4,
//         soul: 0,
//         magi: false,
//         phys: true,
//         tech: false,
//         WIS: 0,
//         STR: 8,
//         DEX: 0,
//         HP: 8,
//         timer: 4,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'TerraByte',
//         category: 'ENTITY',
//         subTypes: ['Verd'],
//         keywords: ['HASTE', 'CHARGE'],
//         rezCost: 3,
//         ash: 0,
//         soul: 0,
//         magi: false,
//         phys: true,
//         tech: false,
//         WIS: 0,
//         STR: 2,
//         DEX: 0,
//         HP: 2,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'PingWin',
//         category: 'ENTITY',
//         subTypes: ['Verd'],
//         keywords: ['STING', 'HYPNO', 'HYPNO'],
//         rezCost: 2,
//         ash: 0,
//         soul: 0,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 1,
//         STR: 0,
//         DEX: 0,
//         HP: 1,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'FinchMark',
//         category: 'ENTITY',
//         subTypes: ['Verd'],
//         keywords: ['SPRINT', 'SPRINT', 'JAWBREAKER', 'AGGRESSIVE'],
//         rezCost: 1,
//         ash: 0,
//         soul: 1,
//         magi: false,
//         phys: false,
//         tech: true,
//         WIS: 0,
//         STR: 0,
//         DEX: 2,
//         HP: 2,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'Crane',
//         category: 'ENTITY',
//         subTypes: ['Verd'],
//         keywords: ['BARRICADE', 'BARRICADE', 'JAW', 'DEFENSIVE'],
//         rezCost: 4,
//         ash: 0,
//         soul: 0,
//         magi: false,
//         phys: false,
//         tech: true,
//         WIS: 0,
//         STR: 0,
//         DEX: 2,
//         HP: 3,
//         timer: 4,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'TurnKey',
//         category: 'ENTITY',
//         subTypes: ['Verd'],
//         keywords: [ 'JAWBREAKER', 'TASTY', 'BONY', 'AGGRESSIVE'],
//         rezCost: 2,
//         ash: 0,
//         soul: 1,
//         magi: false,
//         phys: false,
//         tech: true,
//         WIS: 0,
//         STR: 0,
//         DEX: 3,
//         HP: 3,
//         timer: 4,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'PIDGen',
//         category: 'ENTITY',
//         subTypes: ['Verd'],
//         keywords: [ 'LOOP'],
//         rezCost: 1,
//         ash: 2,
//         soul: 0,
//         magi: true,
//         phys: false,
//         tech: true,
//         WIS: 2,
//         STR: 0,
//         DEX: 2,
//         HP: 2,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'FenIX',
//         category: 'ENTITY',
//         subTypes: ['Verd'],
//         keywords: [ 'ASCENDED','CHARGE', 'CHARGE'],
//         rezCost: 0,
//         ash: 0,
//         soul: 3,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 4,
//         STR: 0,
//         DEX: 0,
//         HP: 4,
//         timer: 3,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'Web Crawler',
//         category: 'ENTITY',
//         subTypes: ['Bug'],
//         keywords: [ 'BARRICADE','BARRICADE', 'JAW', 'DEFENSIVE'],
//         rezCost: 3,
//         ash: 2,
//         soul: 0,
//         magi: false,
//         phys: false,
//         tech: true,
//         WIS: 0,
//         STR: 0,
//         DEX: 4,
//         HP: 3,
//         timer: 3,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'Black Window',
//         category: 'ENTITY',
//         subTypes: ['Bug'],
//         keywords: [ 'VENOM'],
//         rezCost: 3,
//         ash: 0,
//         soul: 1,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 1,
//         STR: 0,
//         DEX: 0,
//         HP: 1,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'SKARab',
//         category: 'ENTITY',
//         subTypes: ['Bug'],
//         keywords: [ 'ASCENDED', 'LOOP', 'CONSTRUCT'],
//         rezCost: 1,
//         ash: 4,
//         soul: 0,
//         magi: false,
//         phys: true,
//         tech: false,
//         WIS: 0,
//         STR: 2,
//         DEX: 0,
//         HP: 1,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'deathHED',
//         category: 'ENTITY',
//         subTypes: ['Bug'],
//         keywords: [ 'BONY', 'BONY', 'STEALTH'],
//         rezCost: 1,
//         ash: 4,
//         soul: 0,
//         magi: false,
//         phys: true,
//         tech: false,
//         WIS: 0,
//         STR: 2,
//         DEX: 0,
//         HP: 1,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'dMonarach',
//         category: 'ENTITY',
//         subTypes: ['Bug'],
//         keywords: [ 'INSPIRE'],
//         rezCost: 1,
//         ash: 0,
//         soul: 2,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 2,
//         STR: 0,
//         DEX: 0,
//         HP: 3,
//         timer: 3,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'HoneyTrap',
//         category: 'ENTITY',
//         subTypes: ['Bug'],
//         keywords: [ 'SLIMY', 'CONSTRUCT', 'BARRICADE'],
//         rezCost: 4,
//         ash: 0,
//         soul: 0,
//         magi: false,
//         phys: false,
//         tech: true,
//         WIS: 0,
//         STR: 0,
//         DEX: 1,
//         HP: 5,
//         timer: 3,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'DragonFi',
//         category: 'ENTITY',
//         subTypes: ['Bug'],
//         keywords: [ 'STING', 'STING', 'STING'],
//         rezCost: 1,
//         ash: 0,
//         soul: 2,
//         magi: false,
//         phys: true,
//         tech: false,
//         WIS: 0,
//         STR: 2,
//         DEX: 0,
//         HP: 2,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'ANTLyre',
//         category: 'ENTITY',
//         subTypes: ['Bug'],
//         keywords: [ 'DEFENSIVE', 'DEVOUR', 'SCAVENGER'],
//         rezCost: 3,
//         ash: 0,
//         soul: 1,
//         magi: false,
//         phys: true,
//         tech: false,
//         WIS: 0,
//         STR: 5,
//         DEX: 0,
//         HP: 3,
//         timer: 3,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'StreamRay',
//         category: 'ENTITY',
//         subTypes: ['Phish'],
//         keywords: [ 'STREAMING', 'STING', 'STING'],
//         rezCost: 3,
//         ash: 0,
//         soul: 1,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 0,
//         STR: 5,
//         DEX: 0,
//         HP: 3,
//         timer: 3,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 4,
//         name: 'FOO Goo',
//         category: 'ENTITY',
//         subTypes: ['Phish'],
//         keywords: [ 'DEFENSIVE', 'JAW', 'SLIMY', 'SLIMY', 'CONTAMINATED'],
//         rezCost: 2,
//         ash: 0,
//         soul: 0,
//         magi: true,
//         phys: false,
//         tech: true,
//         WIS: 1,
//         STR: 0,
//         DEX: 1,
//         HP: 4,
//         timer: 4,
//         text: '',
//         flavor: '',
//     },
//     { //todo
//         id: 27,
//         name: 'Lone Shark',
//         category: 'ENTITY',
//         subTypes: ['Phish'],
//         keywords: [ 'DEBTTOUCH', 'PIRACY'],
//         rezCost: 1,
//         soul: 1,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 7,
//         STR: 0,
//         DEX: 0,
//         HP: 3,
//         timer: 4,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 27,
//         name: 'GELo Phish',
//         category: 'ENTITY',
//         subTypes: ['Phish'],
//         keywords: [ 'GENESIS', 'GENESIS', 'GENESIS'],
//         rezCost: 1,
//         soul: 1,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 7,
//         STR: 0,
//         DEX: 0,
//         HP: 3,
//         timer: 4,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 27,
//         name: 'HyDro',
//         category: 'ENTITY',
//         subTypes: ['Phish'],
//         keywords: [ 'HUSK', 'HUSK'],
//         rezCost: 2,
//         ash: 6,
//         soul: 0,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 7,
//         STR: 0,
//         DEX: 0,
//         HP: 3,
//         timer: 4,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 27,
//         name: 'BLOB Phish',
//         category: 'ENTITY',
//         subTypes: ['Phish'],
//         keywords: [ 'POSTMORTEM'],
//         rezCost: 2,
//         ash: 6,
//         soul: 0,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 7,
//         STR: 0,
//         DEX: 0,
//         HP: 3,
//         timer: 4,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 27,
//         name: 'bluTooth',
//         category: 'ENTITY',
//         subTypes: ['Phish'],
//         keywords: [ 'STREAMING', 'OVERRIDE'],
//         rezCost: 2,
//         ash: 6,
//         soul: 0,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 7,
//         STR: 0,
//         DEX: 0,
//         HP: 3,
//         timer: 4,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 27,
//         name: 'Possesed Doll',
//         category: 'ENTITY',
//         rezCost: 1,
//         soul: 1,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 7,
//         STR: 0,
//         DEX: 0,
//         HP: 3,
//         timer: 4,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 3,
//         name: 'Hell Hound',
//         category: 'ENTITY',
//         rezCost: 2,
//         soul: 1,
//         magi: true,
//         phys: true,
//         tech: true,
//         WIS: 0,
//         STR: 4,
//         DEX: 0,
//         HP: 2,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 1,
//         name: 'Lizardfolk',
//         category: 'ENTITY',
//         rezCost: 2,
//         magi: false,
//         phys: true,
//         tech: false,
//         WIS: 0,
//         STR: 1,
//         DEX: 0,
//         HP: 3,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 2,
//         name: 'Hydra',
//         category: 'ENTITY',
//         rezCost: 4,
//         magi: false,
//         phys: true,
//         tech: false,
//         WIS: 0,
//         STR: 5,
//         DEX: 0,
//         HP: 6,
//         timer: 4,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 0,
//         name: 'Lizardfolk',
//         category: 'ENTITY',
//         rezCost: 2,
//         magi: false,
//         phys: true,
//         tech: false,
//         WIS: 0,
//         STR: 1,
//         DEX: 0,
//         HP: 3,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 12,
//         name: 'Malice',
//         category: 'ENTITY',
//         rezCost: 2,
//         soul: 2,
//         keywords: ['POUNCE'],
//         magi: false,
//         phys: true,
//         tech: false,
//         WIS: 0,
//         STR: 3,
//         DEX: 0,
//         HP: 5,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 19,
//         name: 'Hell Hound',
//         category: 'ENTITY',
//         rezCost: 2,
//         soul: 1,
//         magi: false,
//         phys: true,
//         tech: false,
//         WIS: 0,
//         STR: 4,
//         DEX: 0,
//         HP: 2,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 23,
//         name: 'Curious Acolyte',
//         category: 'ENTITY',
//         rezCost: 3,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 3,
//         STR: 0,
//         DEX: 0,
//         HP: 1,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 24,
//         name: 'Curious Acolyte',
//         category: 'ENTITY',
//         rezCost: 3,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 3,
//         STR: 0,
//         DEX: 0,
//         HP: 1,
//         timer: 2,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 25,
//         name: 'Haunting Siren',
//         category: 'ENTITY',
//         rezCost: 1,
//         ash: 4,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 6,
//         STR: 0,
//         DEX: 0,
//         HP: 8,
//         timer: 3,
//         text: '',
//         flavor: '',
//     },
//     {
//         id: 26,
//         name: 'Haunting Siren',
//         category: 'ENTITY',
//         rezCost: 1,
//         ash: 4,
//         magi: true,
//         phys: false,
//         tech: false,
//         WIS: 6,
//         STR: 0,
//         DEX: 0,
//         HP: 8,
//         timer: 3,
//         text: '',
//         flavor: '',
//     }
// ];

// // Export the array of cards
// export const enemyOne: Card[] = cardList;