import { Card, Category, CostType, EffectType, SkillType, Trigger, Motive } from '../rules/cards';

const cards: Card[] = [
    {
        id: 0,
        name: 'Dreamer',
        category: 'CREATURE',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        WIS: 0,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'CREATURE',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        WIS: 0,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'CREATURE',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        WIS: 0,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'CREATURE',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        WIS: 0,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'CREATURE',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        WIS: 0,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'CREATURE',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        WIS: 0,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'CREATURE',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        WIS: 0,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'CREATURE',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        WIS: 0,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'CREATURE',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        WIS: 0,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'CREATURE',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        WIS: 0,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 3,
        text: '',
        flavor: '',
    }
];

// Export the array of cards
export const draftList: Card[] = cards;