import { Card } from '../rules/cards';

const cards: Card[] = [
    {
        id: 0,
        name: 'Dreamer',
        category: 'ENTITY',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        power: 1,
        HP: 1,
        timer: 1,
        description: '',
        faction: 'gray-border',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'ENTITY',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        power: 1,
        HP: 1,
        timer: 1,
        description: '',
        faction: 'gray-border',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'ENTITY',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        power: 1,
        HP: 1,
        timer: 1,
        description: '',
        faction: 'gray-border',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'ENTITY',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        power: 1,
        HP: 1,
        timer: 1,
        description: '',
        faction: 'gray-border',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'ENTITY',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        power: 1,
        HP: 1,
        timer: 1,
        description: '',
        faction: 'gray-border',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'ENTITY',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        power: 1,
        HP: 1,
        timer: 1,
        description: '',
        faction: 'gray-border',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'ENTITY',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        power: 1,
        HP: 1,
        timer: 1,
        description: '',
        faction: 'gray-border',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'ENTITY',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        power: 1,
        HP: 1,
        timer: 1,
        description: '',
        faction: 'gray-border',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'ENTITY',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        power: 1,
        HP: 1,
        timer: 1,
        description: '',
        faction: 'gray-border',
    },
    {
        id: 0,
        name: 'Dreamer',
        category: 'ENTITY',
        rezCost: 1,
        magi: true,
        phys: true,
        tech: true,
        power: 1,
        HP: 1,
        timer: 1,
        description: '',
        faction: 'gray-border',
    }
];

// Export the array of cards
export const draftList: Card[] = cards;