import { Card, Category, CostType, EffectType, SkillType, Trigger, Motive } from '../rules/cards';

const cardList: Card[] = [
    {
        id: 4,
        name: 'Night Mare',
        category: 'CREATURE',
        rezCost: 4,
        ash: 2,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 6,
        DEX: 0,
        HP: 5,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 27,
        name: 'Possesed Doll',
        category: 'CREATURE',
        rezCost: 1,
        soul: 1,
        magi: true,
        phys: false,
        tech: false,
        WIS: 7,
        STR: 0,
        DEX: 0,
        HP: 3,
        timer: 4,
        text: '',
        flavor: '',
    },
    {
        id: 4,
        name: 'Night Mare',
        category: 'CREATURE',
        rezCost: 4,
        ash: 2,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 6,
        DEX: 0,
        HP: 5,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 27,
        name: 'Possesed Doll',
        category: 'CREATURE',
        rezCost: 1,
        soul: 1,
        magi: true,
        phys: false,
        tech: false,
        WIS: 7,
        STR: 0,
        DEX: 0,
        HP: 3,
        timer: 4,
        text: '',
        flavor: '',
    },
    {
        id: 3,
        name: 'Hell Hound',
        category: 'CREATURE',
        rezCost: 2,
        soul: 1,
        magi: true,
        phys: true,
        tech: true,
        WIS: 0,
        STR: 4,
        DEX: 0,
        HP: 2,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 1,
        name: 'Lizardfolk',
        category: 'CREATURE',
        rezCost: 2,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 1,
        DEX: 0,
        HP: 3,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 2,
        name: 'Hydra',
        category: 'CREATURE',
        rezCost: 4,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 5,
        DEX: 0,
        HP: 6,
        timer: 4,
        text: '',
        flavor: '',
    },
    {
        id: 0,
        name: 'Lizardfolk',
        category: 'CREATURE',
        rezCost: 2,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 1,
        DEX: 0,
        HP: 3,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 12,
        name: 'Malice',
        category: 'CREATURE',
        rezCost: 2,
        soul: 2,
        keywords: ['GUNSLINGER'],
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 3,
        DEX: 0,
        HP: 5,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 19,
        name: 'Hell Hound',
        category: 'CREATURE',
        rezCost: 2,
        soul: 1,
        magi: false,
        phys: true,
        tech: false,
        WIS: 0,
        STR: 4,
        DEX: 0,
        HP: 2,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 23,
        name: 'Curious Acolyte',
        category: 'CREATURE',
        rezCost: 3,
        magi: true,
        phys: false,
        tech: false,
        WIS: 3,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 24,
        name: 'Curious Acolyte',
        category: 'CREATURE',
        rezCost: 3,
        magi: true,
        phys: false,
        tech: false,
        WIS: 3,
        STR: 0,
        DEX: 0,
        HP: 1,
        timer: 2,
        text: '',
        flavor: '',
    },
    {
        id: 25,
        name: 'Haunting Siren',
        category: 'CREATURE',
        rezCost: 1,
        ash: 4,
        magi: true,
        phys: false,
        tech: false,
        WIS: 6,
        STR: 0,
        DEX: 0,
        HP: 8,
        timer: 3,
        text: '',
        flavor: '',
    },
    {
        id: 26,
        name: 'Haunting Siren',
        category: 'CREATURE',
        rezCost: 1,
        ash: 4,
        magi: true,
        phys: false,
        tech: false,
        WIS: 6,
        STR: 0,
        DEX: 0,
        HP: 8,
        timer: 3,
        text: '',
        flavor: '',
    }
];

// Export the array of cards
export const enemyOne: Card[] = cardList;