import { Card, Category, EffectType, SkillType, Trigger } from '../rules/cards';

const enemyOne: Card[] = [
        {
        faction: 'orange-border',
        id: 107, // Unique ID
        name: "BluTooth",
        category: "ENTITY",
        subTypes: ["JAWbreaker"],
        rezCost: 2,
        soul: 3,
        ash: 0,
        runes: 0,
        plot: 0,
        keywords: "Override. Buffer 4, Aggressive.",
        description: "2 Actions ➔ Gain Vengeance 4.",
        magi: false,
        phys: false,
        tech: true,
        power: 2,
        HP: 5,
        timer: 1,
        scrap: 0,
        abilities: [
            { name: "Buffer", amount: 4 },
            { name: "GainVengeance", actionsRequired: 2, amount: 4 },
        ],
        aggressive: true,
        defensive: false,
    },
    {
        faction: 'gray-border',
        id: 407,
        category: "ENTITY",
        name: "Conscripts",
        rezCost: 1,
        soul: 1,
        ash: 0,
        power: 1,
        HP: 6,
        timer: 3,
        subTypes: [],
        keywords: "Defensive.",
        abilities: [],
        description: "",
        defensive: true,
        magi: false,
        phys: true,
        tech: false,
      },
    {
        faction: 'orange-border',
        id: 101,
        name: "SylkWorm",
        category: "ENTITY",
        subTypes: ["JAWbreaker"],
        rezCost: 1,
        soul: 0,
        ash: 5,
        runes: 0,
        plot: 0,
        keywords: "Buffer 2, Aggressive",
        description: "Online enemy entities gain Freeze 2.",
        magi: false,
        phys: false,
        tech: true,
        power: 1,
        aggressive: true,
        HP: 3,
        timer: 2,
        scrap: 0,
        abilities: [
            { name: "Buffer", amount: 2 },
            { name: "SylkWormAura" },
        ],
    },
    {
        faction: 'orange-border',
        id: 104, // Assign a unique ID
        name: "VyperDrive",
        category: "ENTITY",
        subTypes: ["JAWbreaker"],
        rezCost: 1,
        soul: 2,
        ash: 0,
        runes: 0,
        plot: 0,
        keywords: "Drift. Vicious, Aggressive.", // Used for display only
        description: "",
        magi: false,
        phys: false,
        tech: true,
        power: 1,
        HP: 4,
        timer: 2,
        scrap: 0,
        abilities: [
            { name: "Drift" },
            { name: "Vicious", amount: 1 },
        ],
        aggressive: true,
        defensive: false,
    },
    {
        faction: 'orange-border',
        id: 105, // Unique ID
        name: "CatPhish",
        category: "ENTITY",
        subTypes: ["JAWbreaker"],
        rezCost: 2,
        soul: 1,
        ash: 0,
        runes: 0,
        plot: 0,
        keywords: "Pounce. Glitchy, Aggressive.", // For display purposes
        description: "",
        magi: false,
        phys: false,
        tech: true,
        power: 2,
        HP: 3,
        timer: 2,
        scrap: 0,
        abilities: [
            { name: "Glitchy", amount: 1 },
            { name: "Pounce", amount: 1 },
        ],
        aggressive: true,
        defensive: false,
    },
    {
        faction: 'orange-border',
        id: 108, // Unique ID
        name: "Pharmacist",
        category: "ENTITY",
        subTypes: [],
        rezCost: 2,
        soul: 0,
        ash: 2,
        runes: 0,
        plot: 0,
        keywords: "",
        description: "Exhaust ➔ Target friendly Online entity gains Boost 2 and Pounce.",
        magi: false,
        phys: true,
        tech: false,
        power: 1,
        HP: 2,
        timer: 2,
        scrap: 0,
        abilities: [
            {
                name: "BoostAndPounceTargetAlly",
                actionsRequired: 0,
                requiresExhaust: true,
                requiresTarget: true,
                boostAmount: 2,
            },
        ],
        aggressive: false,
        defensive: false,
    },
    {
        faction: 'orange-border',
        id: 109,
        category: "ENTITY",
        name: "Saboteur",
        rezCost: 4,
        soul: 1,
        ash: 0,
        power: 5,
        HP: 4,
        timer: 4,
        abilities: [
            {
                name: "InflictOverloadAndLag",
                overloadAmount: 2,
                lagAmount: 1,
            },
        ],
        description: "Inflict 2 Overload and 1 Lag upon entering play.",
        magi: false,
        phys: true,
        tech: false,
    },
    {
        faction: 'orange-border',
        id: 110,
        category: "ENTITY",
        name: "Poser",
        rezCost: 3,
        soul: 0,
        ash: 0,
        power: 2,
        HP: 2,
        timer: 3,
        keywords: "Impostor. Soulless, Glitchy.",
        abilities: [
            { name: "Impostor" },
            { name: "Soulless" },
            { name: "Glitchy" },
            {
                name: "HackingInflictOverload",
                amount: 3,
            },
        ],
        description: "When you Hack successfully, inflict 3 Overload.",
        magi: false,
        phys: true,
        tech: false,
    },
    {
        faction: 'orange-border',
        id: 111,
        category: "ENTITY",
        name: "Recruiter",
        rezCost: 2,
        soul: 0,
        ash: 3,
        power: 2,
        HP: 3,
        timer: 3,
        keywords: "Stealth.",
        abilities: [
            { name: "Stealth", amount: 1 },
            { name: "DreamersAreImpostors" },
        ],
        description: "Your Dreamers are Impostors.",
        magi: false,
        phys: true,
        tech: false,
    },
    {
        faction: 'orange-border',
        id: 112,
        category: "ENTITY",
        name: "Con Artist",
        rezCost: 3,
        soul: 1,
        ash: 0,
        power: 1,
        HP: 3,
        timer: 3,
        abilities: [
            {
                name: "GainAshAndInflictOverload",
                actionsRequired: 0, // No actions required to activate
                requiresExhaust: true, // Requires exhaustion
                requiresTarget: false, // Does not require a target
                ashAmount: 4,
                overloadAmount: 4,
            },
        ],
        description: "Exhaust ➔ Gain 4 Ash and inflict 4 Overload.",
        magi: false,
        phys: true,
        tech: false,
    },
    {
        faction: 'orange-border',
        id: 121,
        category: "ENTITY",
        name: "Blood Sugar",
        rezCost: 2,
        soul: 0,
        ash: 4,
        power: 3,
        HP: 6,
        timer: 2,
        keywords: "Vicious 3.",
        abilities: [
            {
                name: "Vicious",
                amount: 3,
            },
            {
                name: "OnEnterGainActions",
                actionsGained: 3,
            },
        ],
        description: "Gain 3 Actions.",
        magi: true,
        phys: true,
        tech: false,
    },
    {
        faction: 'orange-border',
        id: 113,
        category: "ENTITY",
        name: "Frost Witch",
        rezCost: 2,
        soul: 1,
        ash: 0,
        power: 2,
        HP: 3,
        timer: 2,
        keywords: "Glitchy, Locality.",
        abilities: [
            { name: "Glitchy" },
            { name: "Locality" },
            { name: "DominanceInflictFreeze", amount: 1 },
        ],
        description: "Dominance ➔ Inflict Freeze 1 on enemy entities.",
        magi: true,
        phys: true,
        tech: false,
    },
    {
        faction: 'gray-border',
        id: 407,
        category: "ENTITY",
        name: "Conscripts",
        rezCost: 1,
        soul: 1,
        ash: 0,
        power: 1,
        HP: 6,
        timer: 3,
        subTypes: [],
        keywords: "Defensive.",
        abilities: [],
        description: "",
        defensive: true,
        magi: false,
        phys: true,
        tech: false,
      },
    {
        faction: 'orange-border',
        id: 115,
        category: "ENTITY",
        name: "Freight Train",
        rezCost: 2,
        soul: 0,
        ash: 0,
        power: 3,
        HP: 4,
        timer: 2,
        abilities: [
            { name: 'Buffer', amount: 3 },
            {
                name: "BoostAllAllies",
                actionsRequired: 0,
                requiresExhaust: true,
                requiresTarget: false,
                effect: {
                    name: "BoostAllAllies",
                    boostAmount: 2,
                },
            },
        ],
        soulless: true,
        locality: true,
        defensive: true,
        keywords: "Buffer 3.",
        description: "Exhaust ➔ Friendly entities gain Boost 2.",
        magi: false,
        phys: true,
        tech: true,
    },
    {
        faction: 'orange-border',
        id: 116,
        category: "ENTITY",
        name: "Leviathan",
        rezCost: 2,
        soul: 3,
        ash: 0,
        power: 3,
        HP: 7,
        timer: 2,
        abilities: [
            { name: 'Buffer', amount: 2 },
            {
                name: 'GainVenomOnInterface',
            },
            {
                name: 'DestroyTargetWithVenom',
                actionsRequired: 0, // No action points required
                requiresExhaust: true, // Requires exhaustion
                requiresTarget: true, // Requires a target
            },
        ],
        keywords: "Buffer 2.",
        description:
            "When you Interface HeadSpace, +3 Venom. Exhaust ➔ Destroy target Online entity with HP less than Venom.",
        magi: true,
        phys: false,
        tech: true,
    },
    {
        faction: 'orange-border',
        id: 117,
        category: "ENTITY",
        name: "Nova Kane",
        rezCost: 2,
        soul: 0,
        ash: 7,
        power: 3,
        HP: 3,
        timer: 4,
        keywords: "Solo 2.",
        abilities: [
            {
                name: "GainStealth",
                type: "manual",
                actionsRequired: 1, // Assuming it requires 1 action to activate
                requiresExhaust: false, // Does not require exhaustion
                requiresTarget: false, // Does not require a target
                effect: {
                    name: "GainStealth",
                    amount: 1,
                },
            }
        ],
        description: "Action ➔ Gain Stealth.",
        solo: 2,
        magi: true,
        phys: false,
        tech: true,
    },
    {
        faction: 'orange-border',
        id: 114,
        category: "ENTITY",
        name: "Dread",
        rezCost: 1,
        soul: 0,
        ash: 6,
        power: 5,
        HP: 3,
        timer: 2,
        abilities: [
            { name: "Deathless" },
            { name: "Buffer", amount: 3 },
            { name: "DominanceInflictBurden", amount: 3 },
            { name: "SurrenderGainBurden", amount: 3 },
        ],
        description: "Dominance ➔ Inflict 3 Burden. Surrender ➔ Gain 3 Burden.",
        magi: true,
        phys: false,
        tech: false,
    },
    {
        faction: 'orange-border',
        id: 122,
        category: "LOCATION",
        name: "Pirate Vessel",
        rezCost: 3,
        soul: 0,
        ash: 0,
        HP: 2,
        keywords: "Crusade.",
        abilities: [
            { name: "Crusade" },
            { name: "GainResourcesOnInterface" }
        ],
        description: "When you Interface HeadSpace, +2 Bits and +2 Ash.",
        magi: false,
        phys: true,
        tech: true,
    },
    {
        faction: 'orange-border',
        id: 123,
        category: "LOCATION",
        name: "Insurgency",
        rezCost: 2,
        soul: 0,
        ash: 0,
        HP: 3,
        keywords: "",
        abilities: [
            {
                name: "DamageTargetPlace",
                type: "manual",
                actionsRequired: 2,
                requiresExhaust: false,
                requiresTarget: true,
                effect: {
                    name: "DamageTargetPlace",
                    damageAmount: 1,
                },
            },
            {
                name: "GainSurgeAndAshOnPlaceDestroyed",
                type: "triggered",
                triggers: ["placeDestroyed"],
            },
        ],
        description:
            "2 Actions ➔ Deal 1 Damage to target Place. Whenever another Place is destroyed, +3 Surge and +3 Ash.",
        magi: true,
        phys: true,
        tech: false,
    },
    {
        faction: 'orange-border',
        id: 124,
        category: "SNIP",
        name: "Precognition",
        rezCost: 2,
        soul: 0,
        ash: 0,
        scrap: 4,
        keywords: "Surgical, Tarot.",
        schemeThreshold: 2, // Scheme 2
        scheming: true,     // Indicates this card can be developed via Scheme
        abilities: [
          {
            name: "GainActionsOnHeadSpaceInterface",
            type: "triggered",
            triggers: ["successfulHack"],
            effect: {
              amount: 3,
            },
          },
        ],
        description:
          "Scheme 2: The first time you Interface HeadSpace each turn gain 3 Actions.",
        magi: true,
        phys: true,
        tech: false,
    },
    {
        faction: 'orange-border',
        id: 118, // Replace with a specific ID if needed
        category: "SNIP",
        name: "Quantum Stabilizer",
        rezCost: 2,
        soul: 0,
        ash: 0,
        scrap: 3,
        abilities: [
            {
                name: "PandoraAccess",
                type: "static",
            },
        ],
        description: "When you Interface Pandora, Interface 1 additional card.",
        magi: true,
        phys: false,
        tech: true,
    },
    {
        faction: 'orange-border',
        id: 119, // Assign a unique ID if needed
        category: "SNIP",
        name: "Data Bomb",
        rezCost: 2,
        soul: 0,
        ash: 0,
        scrap: 1,
        schemeThreshold: 2, // Scheme 2
        scheming: true,
        trap: true,
        development: 0, // Starts with 0 Developments
        abilities: [
            {
                name: "DataBombWhenInterfaced",
                type: "triggered",
                triggers: ["snipAccessed"],
                effect: {
                    overloadPerDevelopment: 2,
                },
            },
            {
                name: "DataBombSacrificeForFreeze",
                type: "manual",
                requiresTarget: true,
                effect: {
                    freezeAmount: 5,
                },
            },
        ],
        description:
            "When Interfaced, inflict 2 Overload for each Development. Scheme 2: Sacrifice ➔ Target entity gains Freeze 5.",
        magi: false,
        phys: true,
        tech: true,
    },
    {
        faction: 'orange-border',
        id: 120,
        category: "SNIP",
        name: "Imitation Game",
        rezCost: 2,
        soul: 0,
        ash: 0,
        scrap: 2,
        abilities: [
            { name: "Impostor" },
            {
                name: "ImitationGameInflictOverload",
                type: "manual",
                effect: {
                    overloadAmount: 3,
                },
            },
        ],
        description: "Inflict 3 Overload.",
        magi: false,
        phys: false,
        tech: true,
    },
    {
        faction: 'orange-border',
        id: 127,
        category: "SYM",
        name: "Adrenochrome",
        runes: 2,
        plot: 2,
        abilities: [{ name: "AdrenochromeAscend" }],
        description: "Ascend ➔ Gain 2 Actions, 3 Ash, and 4 Overload.",
        magi: true,
        phys: true,
        tech: false,
        subTypes: [],
    },
    {
        faction: 'orange-border',
        id: 128,
        category: "SYM",
        name: "Cat Cafe",
        runes: 1,
        plot: 3,
        abilities: [{ name: "CatCafeAscended" }],
        description: "Ascended: Beginning of Turn ➔ Inflict 3 Overload.",
        magi: true,
        phys: true,
        tech: false,
        subTypes: [], // Add subTypes if applicable
    },
    {
        faction: 'orange-border',
        id: 129,
        category: "LANDMARK",
        name: "Wasteland",
        rezCost: 0,
        soul: 0,
        ash: 0,
        HP: 2,
        runes: 2,
        plot: 2,
        abilities: [{ name: "Wasteland" }],
        description: "Stolen, Destroyed ➔ Inflict 1 Wound.",
        magi: false,
        phys: true,
        tech: false,
    },
    {
        faction: 'orange-border',
        id: 130,
        category: "LANDMARK",
        name: "Forgotten Island",
        rezCost: 0,
        soul: 0,
        ash: 0,
        HP: 6,
        runes: 4,
        plot: 5,
        abilities: [{ name: "ForgottenIslandAscend" }],
        description: "Ascend ➔ +10 Bits.",
        magi: true,
        phys: true,
        tech: false,
    },
    {
        faction: 'orange-border',
        id: 131,
        category: "LANDMARK",
        name: "Splinter Faction",
        rezCost: 0,
        soul: 0,
        ash: 0,
        HP: 5,
        runes: 3,
        plot: 4,
        abilities: [{ name: "SplinterFactionAscend" }],
        description: "Ascend ➔ Deal 2 damage to enemy entities.",
        magi: false,
        phys: true,
        tech: true,
    }
];

// Export the array of cards
export default enemyOne;
